.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/general_question.md, .github/PULL_REQUEST_TEMPLATE.md
Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE.
These templates are currently used in mlcommons/chakra.
=> Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

.github/workflows/ci.yml, requirements-dev.txt
Add vulture into `requirements-dev.txt` to fix CI
CI
—
=> Add vulture into requirements-dev.txt

src/cloudai/schema/system/slurm/slurm_system.py, tests/schema/system/slurm/test_slurm_system.py
Refactor SlurmSystem methods for bug fix and add unit tests
1. pytest
2. Ran the nccl-test & nccl-miner on our internal servers.
=> Refactor SlurmSystem methods for bug fix and add unit tests

.github/workflows/ci.yml, conf/v0.6/general/system/example_slurm_cluster.toml, pyproject.toml, requirements-dev.txt, src/cloudai/schema/core/test_template.py, tests/test_acceptance.py
1. Add tests based on sample config files.
2. Add coverage calculation.
—
—
=> Acceptence tests

src/cloudai/__main__.py
Disable grading because it's not ready
--
=> Disable grading until further improvements to grading policy

src/cloudai/__init__.py, src/cloudai/_core/registry.py, src/cloudai/parser/core/system_parser.py, src/cloudai/parser/system_parser/slurm_system_parser.py, src/cloudai/parser/system_parser/standalone_system_parser.py, tests/test_init.py, tests/test_registry.py
`Registry` is a Singleton class that can hold all implementation mappings like system parses or test strategies. All default implementations are registered in CloudAI's `__init_.py` file, but users can easily extend the mapping or even replace default implementation with a custom one.
CI
—
=> Introduce a Registry class to hold implementation mapping

pyproject.toml, requirements.txt
Remove requests from requirements.txt
Requests is no longer used by CloudAI.
```
$ grep "requests" -r
[empty]
```
=> Remove requests from requirements.txt

src/cloudai/report_generator/tool/bokeh_report_tool.py
Add CloudAI prefix to plots
Internally tested with generated NCCL-test plots.
=> Add CloudAI prefix to plots

tests/test_slurm_command_gen_strategy.py
Add tests for `_write_sbatch_script()`.
CI
—
=> Add tests for _write_sbatch_script()

src/cloudai/_core/test.py
Update docstring to comply with coding style and max column length
CI pipelines passing
=> Update docstring to comply with coding style and max column length

conf/v0.6/general/test/nemo_launcher.toml, conf/v0.6/general/test_scenario/chakra_replay.toml, conf/v0.6/general/test_scenario/nccl_test.toml, conf/v0.6/general/test_scenario/nemo_launcher.toml, conf/v0.6/general/test_scenario/nemo_launcher_with_noise.toml, conf/v0.6/general/test_scenario/ucc_test.toml, conf/v0.6/general/test_template/chakra_replay.toml, conf/v0.6/general/test_template/nccl_test.toml, conf/v0.6/general/test_template/nemo_launcher.toml, conf/v0.6/general/test_template/ucc_test.toml, src/cloudai/_core/command_gen_strategy.py, src/cloudai/_core/test.py, src/cloudai/_core/test_scenario_parser.py, src/cloudai/_core/test_template.py, src/cloudai/schema/system/slurm/strategy/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py, src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py, tests/test_slurm_command_gen_strategy.py
Move num_nodes from test template to test scenario
CI pipelines passing. Three tests added.
* test_num_nodes_and_nodes
* test_only_num_nodes
* test_only_nodes
=> Move num_nodes from test template to test scenario

src/cloudai/__init__.py, src/cloudai/_core/base_job.py, src/cloudai/_core/base_runner.py, src/cloudai/_core/exceptions.py, src/cloudai/_core/job_status_result.py, src/cloudai/_core/job_status_retrieval_strategy.py, src/cloudai/_core/registry.py, src/cloudai/_core/test.py, src/cloudai/_core/test_template.py, src/cloudai/_core/test_template_parser.py, src/cloudai/runner/slurm/slurm_runner.py, src/cloudai/runner/standalone/standalone_runner.py, src/cloudai/schema/test_template/common/default_job_status_retrieval_strategy.py, src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py, src/cloudai/schema/test_template/nccl_test/job_status_retrieval_strategy.py, tests/test_job_status_retrieval_strategy.py, tests/test_registry.py
Implement JaxToolboxJobStatusRetrievalStrategy and add corresponding tests
1. Added test cases.
- test_no_profile_stderr_file
- test_missing_pax_status_keyword
- test_no_error_files
- test_missing_e2e_time_keyword
- test_successful_job
2. Tested on a real system manually.
```
...
Job 260664 for test Tests.1 failed: profile_stderr.txt file not found in the specified output directory. This file is expected to be created during the profiling stage of the Grok run. Please ensure the profiling stage completed successfully. Run the generated sbatch script manually to debug.
```
=> Implement JaxToolboxJobStatusRetrievalStrategy and add corresponding tests

conf/v0.6/general/test_template/nemo_launcher.toml
Based on PR 31
This MR is for using the official latest NeMo version
Test by @amaslenn
CI
Test by @jeffnvidia
2.1 Slurm command generation
$ cloudaix --mode run --system_config_path conf/v0.6/general/system/israel_1.toml --test_scenario_path conf/v0.6/general/test_scenario/llama/llama.toml
=> use official online container

src/cloudai/_core/base_installer.py, src/cloudai/_core/install_status_result.py, src/cloudai/schema/test_template/nccl_test/slurm_install_strategy.py, src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py, src/cloudai/schema/test_template/ucc_test/slurm_install_strategy.py, src/cloudai/systems/slurm/strategy/slurm_install_strategy.py, tests/test_slurm_install_strategy.py
Enhance error reporting and formatting in installation
**1. Run**
Before this PR
```
$ cloudai --mode run --system_config_path conf/v0.6/general/system/israel_1.toml --test_scenario_path conf/v0.6/general/test_scenario/nccl_test.toml
Cloud AI has not been installed. Please run install mode first.
Some test templates are not installed.
NeMoLauncher: Not installed
```
After this PR
```
$ cloudai --mode run --system_config_path conf/v0.6/general/system/israel_1.toml --test_scenario_path conf/v0.6/general/test_scenario/nccl_test.toml
Cloud AI has not been installed. Please run install mode first.
Some test templates are not installed.
- NeMoLauncher: The following components are missing:
- Repository at /.../nemo_launcher_mirror.git with commit hash 6528780fba8185bf61e7c2396fdd2331ee5933a1
- …
```
=> Enhance error reporting and formatting in installation

README.md, src/cloudai/__main__.py, src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py, src/cloudai/systems/slurm/slurm_system.py
Replace 'Cloud AI' with 'CloudAI'
CI pipelines passsing
=> Replace 'Cloud AI' with 'CloudAI'

src/cloudai/parser/system_parser/slurm_system_parser.py, tests/test_slurm_system_parser.py
Handle boolean and string values for `cache_docker_images_locally`
Added unit tests
=> Handle boolean and string values for `cache_docker_images_locally`

ci_tools/check_copyright_headers.py, src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py, tests/test_acceptance.py, tests/test_base_installer.py, tests/test_docker_image_cache_manager.py, tests/test_init.py, tests/test_job_status_retrieval_strategy.py, tests/test_job_submission_error.py, tests/test_registry.py, tests/test_report_generation_strategy.py, tests/test_slurm_command_gen_strategy.py, tests/test_slurm_install_strategy.py, tests/test_slurm_system.py, tests/test_slurm_system_parser.py
Update CI tool to include tests directory and add copyright notices
CI pipelines pass
=> Update CI tool to include tests directory and add copyright notices

README.md
Add additional information to user on needed step to add required credentials to NGC containers.
Following #21
=> Add credentials for NGC to README

conf/v0.6/general/test_template/nccl_test.toml
Update NCCL test_template container
Passed full installation + test on real system.
**Commands**
```
python ./cloudaix.py --mode install --system_config_path conf/v0.6/general/system/<>.toml
python ./cloudaix.py --mode run --system_config_path conf/v0.6/general/system/<>.toml--test_scenario_path conf/v0.6/general/test_scenario/nccl_test_shortend.toml
```
=> Update NCCL test_template container

conf/v0.6/general/test_template/ucc_test.toml
Update UCC test_template container
Passed full installation + test on real system.
**Commands**
```
python ./cloudaix.py --mode install --system_config_path conf/v0.6/general/system/<>.toml
python ./cloudaix.py --mode run --system_config_path conf/v0.6/general/system/<>.toml--test_scenario_path conf/v0.6/general/test_scenario/ucc_test_shortend.toml
```
=> Update UCC test_template container

pyproject.toml
Bump version to v0.7.2
Not needed.
=> Bump version to v0.7.2

src/cloudai/util/docker_image_cache_manager.py, tests/test_docker_image_cache_manager.py
Fix bug in `check_docker_image_exists` to correctly prioritize cached files.
The problem was that the `check_docker_image_exists` method checked the Docker image URL even if a cached file existed, potentially causing failures if the URL was invalid despite a valid cached file. 
The fix involves updating the method to prioritize the Docker image URL file path if both the cached file and the URL are valid file paths. Additionally, it ensures that the cached file is used if it exists, regardless of the URL's validity.
Added unit tests.
=> Fix bug in check_docker_image_exists to correctly prioritize cached files

pyproject.toml
Bump version to v0.7.3
Not needed.
=> Bump version to v0.7.3

src/cloudai/schema/test_template/nccl_test/report_generation_strategy.py, tests/test_slurm_report_generation_strategy.py
Fix parsing logic and add unit tests for NCCL test report generation. Previously, NcclTestReportGenerationStrategy could not retrieve the last row properly. This issue is tested with a unit test, as shown below, and fixed by this PR.
**Before bug fix**
```
$ pytest tests/test_slurm_report_generation_strategy.py -s                                                                                                                          
================================================================ test session starts =================================================================                                                                     
platform darwin -- Python 3.10.2, pytest-8.1.1, pluggy-1.5.0                                                 
rootdir: /Users/theo/cloudai …
```
=> Fix parsing logic and add unit tests for NCCL test report generation

pyproject.toml
Bump version to v0.7.4
CI passes
=> Bump version to v0.7.4

pyproject.toml, tests/test_parser.py
=> Bump version to v0.7.5

README.md
Update README with project goals, supported systems, and key concepts
Not needed.
=> Update README with project goals, supported systems, and key concepts

src/cloudai/__main__.py, src/cloudai/_core/base_installer.py, src/cloudai/_core/base_runner.py, src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py, src/cloudai/systems/slurm/slurm_system.py, src/cloudai/util/docker_image_cache_manager.py
Make logging a bit more conscious: do not over-log standard output yet store as much data as possible in log file.
CI
—
=> Make logging a bit more conscious

src/cloudai/util/docker_image_cache_manager.py, tests/test_docker_image_cache_manager.py
Refactor _check_docker_image_accessibility to remove srun usage
**1. CI pipelines pass
2. Ran on a server**
```
$ python ./cloudaix.py --mode install --system-config ...--log-level DEBUG --log-file install.log                                                      
...
[DEBUG] Checking if Docker image exists: docker_image_url='nvcr.io/nvidia/pytorch:24.02-py3', subdir_name='ucc-test', docker_image_filename='ucc_test.sqsh' self.cache_docker_images_locally=False
[DEBUG] Checking Docker image accessibility: enroot import -o /tmp/tmp07doig8c/docker_image.sqsh docker://nvcr.io/nvidia/pytorch:24.02-py3
...
[DEBUG] Docker image URL, nvcr.io/nvidia/pytorch:24.02-py3, is accessible.
...
[INFO] CloudAI is already installed.
```
=> Refactor _check_docker_image_accessibility to remove srun usage

src/cloudai/schema/test_template/nccl_test/job_status_retrieval_strategy.py, tests/test_job_status_retrieval_strategy.py
Update NcclTestJobStatusRetrievalStrategy to improve error messages
CI pipelines pass.
=> Update NcclTestJobStatusRetrievalStrategy to improve error messages

src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py, tests/test_job_status_retrieval_strategy.py
Update JaxToolboxJobStatusRetrievalStrategy to improve error messages
CI pipelines pass
=> Update JaxToolboxJobStatusRetrievalStrategy to improve error messages

pyproject.toml
Bump version to v0.7.7
CI pipelines pass
=> Bump version to v0.7.7

src/cloudai/util/docker_image_cache_manager.py, tests/test_docker_image_cache_manager.py
Handle 401 Unauthorized error with detailed instructions for Docker image access
CI passes
=> Handle 401 Unauthorized error with detailed instructions for Docker image access

pyproject.toml
Bump version to v0.7.8
CI passes
=> Bump version to v0.7.8

pyproject.toml
Bump version to v0.7.9
CI passes
=> Bump version to v0.7.9

pyproject.toml
Bump version to v0.7.10
CI passes
=> Bump version to v0.7.10

README.md
Enhance Quick Start guide for Docker repo access and API key
Not needed.
=> Enhance Quick Start guide for Docker repo access and API key

src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py, tests/test_job_status_retrieval_strategy.py
Add pyxis mktemp error handling and test cases in JaxToolbox strategy
Added unit tests. CI pipelines pass.
=> Add pyxis mktemp error handling and test cases in JaxToolbox strategy

USER_GUIDE.md
Add section on downloading NeMo datasets to USER_GUIDE.md
Not needed
=> Add section on downloading NeMo datasets to USER_GUIDE.md

USER_GUIDE.md
Enhance USER_GUIDE.md with system schema description and troubleshooting steps
Not needed
=> Enhance USER_GUIDE.md with system schema description and troubleshooting steps

USER_GUIDE.md
Add section on describing a test scenario to USER_GUIDE.md
Not needed
=> Add section on describing a test scenario to USER_GUIDE.md

.github/workflows/ci.yml, pyproject.toml, src/cloudai/_core/base_runner.py, tests/test_base_runner.py
Update BaseRunner to include scenario name in output directory
Added unit tests and CI passes.
=> Update BaseRunner to include scenario name in output directory

pyproject.toml
Bump version to v0.7.11
Not needed.
=> Bump version to v0.7.11

README.md
Update README: add mandatory args test-templates-dir and tests-dir
Not needed.
=> Update README: add mandatory args test-templates-dir and tests-dir

USER_GUIDE.md
Update NeMo launcher troubleshooting guide for clarity and conciseness
Not needed.
=> Update NeMo launcher troubleshooting guide for clarity and conciseness

pyproject.toml
Bump version to v0.7.12
Not needed
=> Bump version to v0.7.12

USER_GUIDE.md
Added JaxToolbox (Grok) troubleshooting steps
Not needed
=> Added JaxToolbox (Grok) troubleshooting steps

src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py, tests/test_slurm_command_gen_strategy.py
* Improve tokenizer path handling in NeMo Launcher Slurm strategy
* This PR relies on https://github.com/NVIDIA/cloudai/pull/134
CI passes
=> Improve tokenizer path handling in NeMo Launcher Slurm strategy

src/cloudai/_core/test_template_parser.py
Remove identical if-else branches
CI
—
=> Remove identical if-else branches

src/cloudai/_core/base_runner.py, tests/test_acceptance.py
Make sure to dry-run all tests in a test scenario. In the latest main branch, dry-run does not run all tests in a test scenario because of missing `await self.handle_job_completion(job)`.
```
$ python ./cloudaix.py --mode dry-run --system-config conf/v0.6/general/system/obfuscated.toml --test-templates-dir conf/v0.6/general/test_template --tests-dir conf/v0.6/general/test --test-scenario conf/v0.6/general/test_scenario/nccl_test.toml 
[INFO] System configuration file: conf/v0.6/general/system/obfuscated.toml
[INFO] Test templates directory: conf/v0.6/general/test_template
[INFO] Tests directory: conf/v0.6/general/test
[INFO] Test scenario file: conf/v0.6/general/test_scenario/nccl_test.toml
...
[INFO] Initializing Runner
[INFO] …
```
=> Make sure to dry-run all tests in a test scenario

src/cloudai/util/docker_image_cache_manager.py, tests/test_docker_image_cache_manager.py
Handle disk quota exceeded error in cache_docker_image method
Added unit tests.
=> Handle disk quota exceeded error in cache_docker_image method

src/cloudai/_core/test_template_strategy.py
Remove unused properties from `TestTemplateStrategy`.
CI
—
=> Remove unused properties from TestTemplateStrategy

src/cloudai/_core/test_parser.py, src/cloudai/_core/test_scenario_parser.py
Enhance error messages to provide guidance for missing schemas
CI passes
=> Enhance error messages to provide guidance for missing schemas

pyproject.toml
Bump version to v0.7.14
CI passes
=> Bump version to v0.7.14

conf/test_template/nemo_launcher.toml
use latest version of NeMo launcher : 24.05.01
$ python ./cloudaix.py --mode run --system-config ... --test-templates-dir conf/v0.6/general/test_template --tests-dir conf/v0.6/general/test --test-scenario conf/v0.6/general/test_scenario/llama/llama3_70B.toml 
...
Test Name: llama3_70B
Description: llama
[INFO] Initializing Runner
...
=> update container version

src/cloudai/systems/slurm/slurm_system.py
Enhance job status error message for clarity and user guidance
CI passes
=> Enhance job status error message for clarity and user guidance

requirements-dev.txt, src/cloudai/_core/base_runner.py
Upgrade `pyright`, fix warning.
CI
—
=> Upgrade pyright, fix warning

pyproject.toml
Automatically define version from the git tags.
—
—
=> Automatically define version from the git tags

src/cloudai/_core/system.py, src/cloudai/_core/test_template_strategy.py, src/cloudai/systems/slurm/slurm_system.py, src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py, src/cloudai/systems/standalone_system.py
This PR relies on https://github.com/NVIDIA/cloudai/pull/176
- Added install_path and global_env_vars to the System class.
- Integrated global_env_vars into TestTemplateStrategy.
**1. CI**
CI passes. I believe the changes in the PR are covered by the existing unit tests.
**2. Ran on a system**
Sleep
```
python cloudaix.py --mode run --system-config conf/v0.6/general/system/system.toml --test-templates-dir conf/v0.6/general/test_template --tests-dir conf/v0.6/general/test --test-scenario conf/v0.6/general/test_scenario/sleep.toml 
[INFO] System configuration file: conf/v0.6/general/system/system.toml
[INFO] Test templates directory: conf/v0.6/general/test_template
[INFO] Tests directory: conf/v0.6/general/test
[INFO] Test scenario file: conf/v0.6/general/test_scenario/sleep.toml
[INFO] …
```
=> Move Common Variables to System class and TestTemplateStrategy

src/cloudai/__init__.py, src/cloudai/_core/base_runner.py, src/cloudai/runner/kubernetes/kubernetes_runner.py, src/cloudai/schema/test_template/nccl_test/__init__.py, src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py, src/cloudai/systems/kubernetes/kubernetes_system.py, tests/test_init.py
* Add NCCL test templates.
* Store output log files upon job completion.
1. CI passes.
2. https://github.com/Mellanox/cloudaix/pull/39#issue-2503854408
=> Update NCCL Test Templates and Introduce Kubernetes-Specific Strategies

tests/test_slurm_command_gen_strategy.py
Add unit test for the reservation feature
CI
=> add test for the reservation feature

src/cloudai/_core/base_runner.py, src/cloudai/_core/runner.py
Log Runner Initialization with Run Mode Indication in BaseRunner. Requested by Dmitry Kuzmin at https://redmine.mellanox.com/issues/3991308
CI
=> Log Runner Initialization with Run Mode Indication in BaseRunner

pyproject.toml
Exclude abstract methods from coverage.
CI
—
=> Exclude abstract methods from coverage

src/cloudai/installer/slurm_installer.py
This PR removes a configuration file generated during installation. When CloudAI is installed, `.cloudai.toml` is generated in the user’s home directory. Currently, `.cloudai.toml` is not used and empty, so there is no reason to keep the file. This file is supposed to be created only after the successful installation of all test templates. Therefore, if a single test template fails to install, the file will not be created. Whenever users attempt to run CloudAI test scenarios, CloudAI will inform them that the file is missing, implying that CloudAI has not been fully installed. Daria mentioned that this is a blocking issue in the verification process, so the PR removes the file.
https://redmine.mellanox.com/issues/4082388
CI passes.
=> Remove Config File Handling and TOML Dependency from SlurmInstaller

src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py, tests/test_slurm_command_gen_strategy.py
Enhance error handling for missing default_partition
CI passes
=> Enhance Error Handling for Missing default_partition

conf/common/test/gpt3_40b.toml, conf/common/test/llama2_70b.toml
Rename NeMo-related TOML configurations to reflect the exact model
**[TODOs]**
* First, we need to make sure we are on the same page. Otherwise, we should discuss.
* Second, we need to reach out to anyone using GPT- or LLaMA-related configurations to confirm everything is functioning properly.
=> Rename NeMo-related TOML configurations to reflect the exact model

src/cloudai/installer/slurm_installer.py, src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py, src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py, src/cloudai/systems/slurm/strategy/slurm_install_strategy.py, tests/test_slurm_command_gen_strategy.py, tests/test_slurm_install_strategy.py
Expect `SlurmSystem` in respective cmd_gen and installer classes.
CI
—
=> Expect SlurmSystem in respective cmd_gen and installer classes

src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py, src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
Minor refactoring on SlurmCommandGenStrategy
CI passes
=> Minor refactoring on SlurmCommandGenStrategy

conf/common/system/kubernetes_cluster.toml, src/cloudai/runner/kubernetes/kubernetes_job.py, src/cloudai/runner/kubernetes/kubernetes_runner.py, src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py, src/cloudai/systems/kubernetes/kubernetes_system.py, src/cloudai/test_definitions/sleep.py, tests/test_kubernetes_system.py
Resolve K8s comments in https://github.com/NVIDIA/cloudai/pull/180
* https://github.com/NVIDIA/cloudai/pull/180#discussion_r1738545435
* https://github.com/NVIDIA/cloudai/pull/180#discussion_r1739006879
1. CI passes
2. Tested on a K8s system
https://github.com/Mellanox/cloudaix/pull/66
=> Resolve K8s Comments (Part 1)

tests/slurm_command_gen_strategy/test_nemo_launcher.py
Refactor NeMoLauncherSlurmCommandGenStrategy unit tests
CI passes
=> Refactor NeMoLauncherSlurmCommandGenStrategy unit tests

src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
Refactor container load and run command generation into separate functions
1. CI passes
2. Manual run
=> Refactor JaxToolboxSlurmCommandGenStrategy

src/cloudai/__init__.py, src/cloudai/test_definitions/__init__.py, src/cloudai/test_definitions/gpt.py, src/cloudai/test_definitions/grok.py, src/cloudai/test_definitions/jax_toolbox.py, src/cloudai/test_definitions/nemotron.py, tests/slurm_command_gen_strategy/test_jax_toolbox.py, tests/test_init.py
Move JaxToolbox-related test definitions to CloudAI
1. CI passes
2. Manual run
=> Move JaxToolbox-related test definitions to CloudAI

src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py, src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py, src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py, src/cloudai/test_definitions/gpt.py, src/cloudai/test_definitions/jax_toolbox.py, tests/slurm_command_gen_strategy/test_common.py, tests/slurm_command_gen_strategy/test_jax_toolbox.py
Remove the duplicated code in the *SlurmCommandGenStrategy classes.
1. CI passes
2. Manual runs (NCCL / Grok)
=> Refactor SlurmCommandGenStrategy (_write_sbatch_script)

tests/slurm_command_gen_strategy/test_jax_toolbox.py
Refactor JaxToolboxSlurmCommandGenStrategy unit tests for consistency across unit tests.
CI passes
=> Refactor JaxToolboxSlurmCommandGenStrategy unit tests

src/cloudai/cli/__init__.py, src/cloudai/cli/cli.py, src/cloudai/cli/handlers.py, tests/test_cli.py
Remove deprecated verify modes.
CI
—
=> Remove deprecated verify modes

README.md
Fix README on `verify-*` modes. Internal [bug](https://redmine.mellanox.com/issues/4125865).
Manual
—
=> Fix README on verify-* modes

README.md
List supported tests per each system in README. Closes #272.
Manual
—
=> List supported tests per each system in README

tests/test_parser.py
Remove dead code from tests/test_parser.py
CI passes
=> Remove dead code from `tests/test_parser.py`

CONTRIBUTING.md
Fixed places in CONTRIBUTING.md that still reflects Gitlab items. 
N/A
N/A
=> Update CONTRIBUTING.md to reflect Gitlab->Github migration

src/cloudai/_core/test_scenario_parser.py, src/cloudai/parser.py, tests/test_test_scenario.py
Use pathlib.Path for TestScenarioParser for consistency.
CI passes
=> Use pathlib.Path for TestScenarioParser

src/cloudai/_core/test_template.py
Removed the following comment because install strategy has been completely removed from CloudAI
```
install_strategy (InstallStrategy): Strategy for installing test prerequisites.
```
CI passes
=> Remove obsolete comment

src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py, tests/ref_data/nemo-launcher.sbatch, tests/test_acceptance.py
1. Fixed cmd generation for Nemo Launcher.
2. Add acceptance tests.
CI
—
=> Fix Nemo Launcher cmd generation, add tests

.github/workflows/ci.yml, src/cloudai/_core/base_runner.py
* Fix dry-run mode broken in #301.
* Bug fix for https://redmine.mellanox.com/issues/4175225
1. Manual
2. Extended CI
—
=> Fix broken dry-run mode

src/cloudai/cli/handlers.py
This ensures real paths construction and helps avoid misleading warnings about "possibly missing installation".
1.  Manually
2. CI
—
=> Check if artifacts installed for dry-run mode

src/cloudai/_core/test_scenario_parser.py
Add a field for SOL in test scenario for internal use case.
CI
=> Add sol_path to test scenario

USER_GUIDE.md
Add test hooks to USER_GUIDE.md
https://redmine.mellanox.com/issues/4207126
Not needed
=> Add test hooks to USER_GUIDE.md

tests/test_slurm_system.py
Extend tests for job status checking.
CI
—
=> Extend tests for job status checking

src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py, tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Add container_mounts to final_cmd_args for NCCL_TOPO_FILE
1. Added a unit test
2. Ran on a system
=> Add container_mounts to final_cmd_args for NCCL_TOPO_FILE

conf/common/test/nccl_test_all_gather.toml, conf/common/test/nccl_test_reduce_scatter.toml, conf/hook/test/nccl_test_all_gather.toml
Replace NCCL_TEST_SPLIT_MASK with NCCL_TESTS_SPLIT_MASK
CI passes
=> Replace NCCL_TEST_SPLIT_MASK with NCCL_TESTS_SPLIT_MASK

.github/workflows/ci.yml, pyproject.toml, src/cloudai/_core/base_installer.py, src/cloudai/cli/handlers.py, src/cloudai/util/__init__.py, tests/test_base_installer.py
Check RW permissions during `is_installed` and results folder.
This addresses https://redmine.mellanox.com/issues/4237194.
1. CI.
2. Manual for results folder.
—
=> Check RW permissions for install and results folders

src/cloudai/_core/test_scenario_parser.py, tests/test_test_scenario.py
Reflect Andrei's comments for PR345: https://github.com/NVIDIA/cloudai/pull/345/files#r1924975398
CI passes
=> Reflect Andrei's comments for PR345

conf/common/test/dse_jaxtoolbox_grok.toml
Updates the docker url to valid one. For this bug: https://redmine.mellanox.com/issues/4195137#change-34960967
CI/CD
=> fix the docker url for dse [for QA]

README.md, USER_GUIDE.md, doc/DEV.md
I went over the files and did some formatting changes so the document will be more user friendly and easier to read. I also corrected some typos. Please review the changes I did and let me know if there is anything else to do. 
Thanks!
N/A
N/A
=> Docs Review - Suggested Changes

conf/release/nemo_acceptance/test/gpt3_126m_mock.toml, conf/release/nemo_acceptance/test/gpt3_126m_pile.toml, conf/release/nemo_acceptance/test/nccl_test_all_reduce_loopback.toml, conf/release/nemo_acceptance/test_scenario/gpt3_126m_mock.toml, conf/release/nemo_acceptance/test_scenario/gpt3_126m_pile.toml, conf/release/nemo_acceptance/test_scenario/nccl_test_loopback.toml
Move conf/staging/nemo/ to CloudAI
https://github.com/Mellanox/cloudaix/pull/156
https://nvidia.slack.com/archives/C07N8N0LKK5/p1737744385926749
Not needed
=> Move conf/staging/nemo/ to CloudAI

USER_GUIDE.md, src/cloudai/_core/test.py, src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py, tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Support custom mounts for slurm container jobs.
1. CI.
2. Manual run with custom configs.
—
=> Support custom mounts for slurm container jobs

USER_GUIDE.md
Update NeMo dataset link in USER_GUIDE.md
CI passes
=> Update NeMo dataset link in USER_GUIDE.md

src/cloudai/systems/slurm/slurm_system.py
Remove unused code from SlurmSystem.
CI.
This is needed as part of removing nodes list from partition definition.
=> Remove unused code from SlurmSystem

tests/ref_data/megatron-run.sbatch
Fix megatron ref sbatch. CI didn't restart for updated main branch, so we've missed it.
CI.
—
=> Fix megatron ref sbatch

src/cloudai/workloads/nemo_launcher/nemo_launcher.py, tests/ref_data/nemo-launcher.sbatch
Update NeMo docker image to nvcr.io/nvidia/nemo:24.05.01
https://nvidia.slack.com/archives/C088QU7CE3S/p1741041302798069?thread_ts=1741036508.812379&cid=C088QU7CE3S
1. CI passes
2. Tested on EOS and IL-1
=> Update NeMo docker image to nvcr.io/nvidia/nemo:24.12.01

src/cloudai/installer/slurm_installer.py, tests/test_slurm_installer.py
While investigating [internal bug](https://redmine.mellanox.com/issues/4340754), extended logging and added more tests.
CI
—
=> More logs and tests for uninstall logic

src/cloudai/workloads/nccl_test/performance_report_generator.py, src/cloudai/workloads/nccl_test/report_generation_strategy.py, tests/report_generation_strategy/test_nccl_report_generation_strategy.py
Refactor NcclTestReportGenerationStrategy. It will enable us to add more report generators to CloudAIX.
* [Follow-up PR](https://github.com/Mellanox/cloudaix/pull/177)
1. CI passes
2. Ran on EOS
```
$ cloudai run --system-config conf/common/system/eos.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nccl_test.toml 
```
Manually investigated the output.
=> Refactor NcclTestReportGenerationStrategy

conf/common/system/example_slurm_cluster.toml, src/cloudai/installer/standalone_installer.py, tests/test_job_submission_error.py, tests/test_parser.py, tests/test_standalone_installer.py
=> Fix copyright years

src/cloudai/_core/reporter.py
Use abs path to jinja2 template.
1. Manually.
2. CI.
Include any other notes or comments about the pull request here. This can include challenges faced, future considerations, or context that reviewers might find helpful.
=> Use abs path to jinja2 template

src/cloudai/_core/test.py, src/cloudai/cli/handlers.py, tests/test_job_type_handler.py
Make `is_dse_job` a property of TestDefinition.
CI.
—
=> Make is_dse_job a property of TestDefinition

pyproject.toml, src/cloudai/_core/configurator/cloudai_gym.py, src/cloudai/_core/report_generation_strategy.py, src/cloudai/_core/test.py, src/cloudai/_core/test_scenario.py, src/cloudai/_core/test_scenario_parser.py, src/cloudai/workloads/nemo_run/report_generation_strategy.py, tests/report_generation_strategy/test_nemo_run_report_generation_strategy.py, tests/test_cloudaigym.py, tests/test_test_scenario.py
Introduce metrics based on parsed data. Metrics a way to get some data programmatically, it can be used for DSE or report generation.
CI.
—
=> Reporter-based metrics

src/cloudai/installer/slurm_installer.py, tests/test_slurm_installer.py
Need to also check the content.
CI.
—
=> Fix installation check for File

src/cloudai/systems/slurm/slurm_system.py
Fix unknown state of the group nodes: `groups` property always initialized nodes with default state which was never updated. Now nodes' state is taken from partition which is updated in `update()` method.
1. CI
2. Manual runs on IL1.
—
=> Fix unknown state of the group nodes

src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py, src/cloudai/workloads/nccl_test/kubernetes_json_gen_strategy.py, src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
Replace pyright ignores with explicit type handling
CI passes
=> Replace pyright ignores with explicit type handling

src/cloudai/_core/test_template.py, src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py, tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Move Slurm-specific methods to SlurmCommandGenStrategy
Follow up for https://github.com/NVIDIA/cloudai/pull/450
Discussion: https://github.com/NVIDIA/cloudai/pull/450#discussion_r2027315601
CI passes
=> Move Slurm-specific methods to SlurmCommandGenStrategy

.github/workflows/ci.yml, src/cloudai/_core/base_runner.py
Restore dry-run on system without slurm.
CI (extended)
—
=> Restore dry-run on system without slurm

src/cloudai/cli/handlers.py
Add context manager to ensure kube config exists
Bug fix for https://redmine.mellanox.com/issues/4136135
CI passes
=> Add context manager to ensure kube config exists

src/cloudai/workloads/nemo_run/report_generation_strategy.py
Add Bokeh report generation to NeMoRunReportGenerationStrategy class
Requested by @srinivas212 for LLMB.
1. CI passes
2. TODO Ran on OCI
```
$ python cloudaix.py run --system-config conf/staging/llmb/system/oci.toml \
--tests-dir conf/staging/llmb/test  \
--test-scenario conf/staging/llmb/test_scenario/nemo2.0_llama3_70b_fp8.toml 
```
```
$ ls
cloudai_nemorun_bokeh_report.html  mapping-stderr.txt  metadata  report_data.json  slurm-job.toml  stdout.txt
cloudai_sbatch_script.sh           mapping-stdout.txt  pre_test  report.txt        stderr.txt
```
=> Add Bokeh report generation to NeMoRunReportGenerationStrategy class

src/cloudai/_core/test_scenario.py, tests/test_cloudaigym.py
Address comments from #513. @srivatsankrishnan please let me know if that covers all you requests. I've addressed ones that I agree with and ready to discuss others, see my comments in #513.
CI
—
=> Address comments from #513

src/cloudai/util/docker_image_cache_manager.py, tests/test_docker_image_cache_manager.py
Set srun job name to "<account>-CloudAI_install_docker_image.%Y%m%d_%H%M%S"
https://redmine.mellanox.com/issues/4427743
1. CI passes
2. Ran on an internal server.
https://docs.google.com/document/d/1Qfk2D9dLq2shrYDZj31FeqcNgKK3YSNF__FXB4izBGA/edit?usp=sharing
=> Set srun job name to "<account>-CloudAI_install_docker_image.%Y%m%d_%H%M%S"

src/cloudai/workloads/triton_inference/report_generation_strategy.py
Fix DeepSeekR1 inference report. Remove the warning message. Daria will treat this warning as a bug.
```
[WARNING] Skipping 'results/deepseek_r1_2025-06-05_12-42-23/Tests.1/0', can't handle with strategy=TritonInferenceReportGenerationStrategy.
```
```
$ python cloudaix.py run --system-config conf/common/system/cw.toml --tests-dir conf/staging/llmb/test --test-scenario conf/staging/llmb/test_scenario/deepseek_r1.toml
[INFO] System Name: Coreweave
[INFO] Test Scenario Name: deepseek_r1
[INFO] Test Scenario: deepseek_r1
Test Name: deepseek_r1
Description: deepseek_r1
[INFO] Running test: …
```
=> Fix DeepSeekR1 inference report

pyproject.toml, src/cloudai/registration.py, src/cloudai/util/lazy_imports.py, src/cloudai/util/nixl_report_template.jinja2, src/cloudai/workloads/nixl_bench/__init__.py, src/cloudai/workloads/nixl_bench/nixl_summary_report.py, tests/test_init.py
New report collect all NIXL runs from a scenario and builds charts and tables based on its results.
1. CI.
2. Manual runs and review of the new report.
—
=> Add NIXL summary report

src/cloudai/workloads/nccl_test/performance_report_generation_strategy.py, tests/report_generation_strategy/test_nccl_performance_report_generation_strategy.py
Update regex to correctly extract full GPU type names including suffixes and variants
https://redmine.mellanox.com/issues/4496921
CI passes
=> Update regex to correctly extract full GPU type names including suffixes and variants

src/cloudai/systems/slurm/slurm_command_gen_strategy.py, tests/ref_data/nemo-run-no-hook.sbatch, tests/ref_data/nemo-run-pre-test.sbatch, tests/ref_data/nemo-run-vboost.sbatch, tests/ref_data/nixl-perftest.sbatch, tests/ref_data/triton-inference.sbatch, tests/test_slurm_system.py
Preserve the order of environment variables specified in the system schema
[RM4554483](https://redmine.mellanox.com/issues/4554483)
CI passes
=> Preserve the order of environment variables specified in the system schema

pyproject.toml
Bump default version to v1.4.
CI
—
=> Bump default version to v1.4

src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
The purpose of this FR is to log the mapping between physical nodes and their assigned roles. A separate file named node_roles.log should be created to track this mapping.
[RM4551176](https://redmine.mellanox.com/issues/4551176)
1. CI passes
2. Run on EOS
```
$ python cloudaix.py install --system-config conf/common/system/eos.toml --tests-dir conf/staging/ai_dynamo/test --test-scenario conf/staging/ai_dynamo/test_scenario/deepseek_r1_distill_llama_8b.toml
$ python cloudaix.py run --system-config conf/common/system/eos.toml --tests-dir conf/staging/ai_dynamo/test --test-scenario conf/staging/ai_dynamo/test_scenario/deepseek_r1_distill_llama_8b.toml
```
```
$ cat node_roles.log
eos0458,frontend
eos0504,prefill
eos0498,prefill
eos0458,decode
``` …
=> Log mapping between AI Dynamo nodes and roles

src/cloudai/registration.py, src/cloudai/systems/slurm/single_sbatch_runner.py, src/cloudai/workloads/nixl_perftest/nixl_perftest.py, src/cloudai/workloads/nixl_perftest/report_generation_strategy.py, src/cloudai/workloads/nixl_perftest/slurm_command_gen_strategy.py, tests/ref_data/nixl-perftest.sbatch, tests/slurm_command_gen_strategy/test_nixl_perftest_slurm_command_gen_strategy.py, tests/test_test_scenario.py
1. Use per rank env vars.
2. Add dummy reporter to enable DSE.
3. Add constraint check for decode/prefill parallelism config.
1. CI (updated).
4. Manual dry-run to check generated sbatch.
Config example:
```toml
name = "nixl-ct-perftest"
[[Tests]]
id = "nixl-ct-perftest"
name = "NIXL-ct-perftest"
description = "NIXL CT Perftest"
test_template_name = "NixlPerftest"
[Tests.cmd_args]
docker_image_url="url.com/docker:tag"
subtest="sequential-ct-perftest"
etcd_path="etcd"
num_user_requests=2
batch_size=1
num_prefill_nodes=1
num_decode_nodes=1
model="model-name"
[Tests.extra_env_vars]
CUDA_VISIBLE_DEVICES = "$SLURM_LOCALID"
```
Run command:
```bash
uv run cloudai run --system-config conf/common/system/example_slurm_cluster.toml --test-scenario nixl-perftest.toml
```
=> Update NIXL perftest workload

.github/workflows/ci.yml, doc/conf.py, doc/index.md, doc/workloads/ai_dynamo.rst, doc/workloads/bash_cmd.rst, doc/workloads/chakra_replay.rst, doc/workloads/index.md, doc/workloads/nccl.rst, doc/workloads/nemo_run.rst, doc/workloads/nixl_bench.rst, doc/workloads/nixl_kvbench.rst, doc/workloads/nixl_perftest.rst, doc/workloads/sleep.rst, doc/workloads/slurm_container.rst, pyproject.toml
1. Add documentation for workloads.
2. Add check if doc can be built to CI.
1. CI
2. Manual doc build and review.
—
=> Add documentation for workloads

doc/USER_GUIDE.md, doc/workloads/ucc.rst
Also restore USER_GUIDE mistakenly removed in #690.
CI
—
=> Add more documentation

README.md, doc/index.md
Fix install/uninstall commands examples in doc.
Fixes [internal bug](https://redmine.mellanox.com/issues/4641265).
n/a
—
=> Fix install/uninstall commands examples in doc
