NVIDIA/cloudai

- src/cloudai/schema/test_template/jax_toolbox/report_generation_strategy.py
- tests/schema/test_template/jax_toolbox/test_report_generation_strategy.py
1. Collection of standard deviation in the JaxToolbox report generation strategy.
2. Update to stats collection, dropping the initial 10 epochs to avoid inconsistencies and reduce profiling overhead.
3. Added unit tests for JaxToolbox report generation (Guided by @amaslenn. I appreciate it!)
```
$ python -m pytest -vv tests      
========================================================================================================= test session starts =========================================================================================================
platform darwin -- Python 3.10.2, pytest-8.1.1, pluggy-1.5.0 -- /Users/theo/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/theo/cloudai
configfile: pyproject.toml
plugins: typeguard-2.13.3, mock-3.14.0, anyio-4.2.0
collected …
```
> Enhance JaxToolbox report generation and update stats collection

- src/cloudai/runner/core/runner.py
- tests/runner/core/test_runner.py
Allow overriding of runner mappings in Runner class
```
$ python -m pytest -vv tests
========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.10.2, pytest-8.1.1, pluggy-1.5.0 -- /Users/theo/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/theo/cloudai
configfile: pyproject.toml
plugins: typeguard-2.13.3, mock-3.14.0, anyio-4.2.0
collected 41 items                                                                                                                                                       
tests/runner/core/test_runner.py::test_register_multiple_runners PASSED …
```
> Allow overriding of runner mappings in Runner class

- src/cloudai/schema/test_template/nccl_test/report_generation_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/report_generation_strategy.py
- src/cloudai/schema/test_template/ucc_test/report_generation_strategy.py
Rename report file names to include 'cloudai' prefix
```
$ cloudai --mode generate-report --output_path ~/Downloads/2024-04-17_22-13-25/ --system_config_path [system_config_path] --test_scenario_path [test_scenario_path]
$ cd ~/Downloads/2024-04-17_22-13-25/
$ ls  | grep report
cloudai_nccl_test_bokeh_report.html
```
> Rename report file names to include 'cloudai' prefix

- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- tests/test_slurm_command_gen_strategy.py
1. Update docker support for Nemo/Nccl testing
2. This PR depends on #17.
**1. Test by @amaslenn** 
CI
**2. Test by @TaekyungHeo** 
**2.1 Slurm command generation for a given URL**
```
[cmd_args.docker_image_url]
type = "str"
default = [URL]
```
```
$ cloudaix --mode dry-run --system_config_path ... --test_scenario_path conf/v0.6/general/test_scenario/nemo_launcher.toml 
```
```
... container=**[installed_docker_image_path]**
```
**2.1 Slurm command generation for a given path**
```
[cmd_args.docker_image_url]
type = "str"
default = [local_file_path]
```
```
$ cloudaix --mode dry-run --system_config_path ...--test_scenario_path conf/v0.6/general/test_scenario/nemo_launcher.toml 
```
```
... container=[local_file_path]
```
—
> Update docker support for Nemo/Nccl testing

- src/cloudai/report_generator/tool/csv_report_tool.py
- src/cloudai/schema/test_template/nccl_test/report_generation_strategy.py
- tests/test_csv_report_tool.py
- Added `CSVReportTool` for generating CSV reports and implemented unit tests for it.
- Updated `NcclTestReportGenerationStrategy` to generate CSV reports using the new `CSVReportTool` alongside existing Bokeh reports.
1. Added unit tests
2. Generated reports
```
$ cloudai ... --mode=generate-report ... 
$ find . -name '*report*'
./Tests.1/0/cloudai_nccl_test_report.csv
./Tests.1/0/cloudai_nccl_test_bokeh_report.html
./Tests.3/0/cloudai_nccl_test_report.csv
./Tests.3/0/cloudai_nccl_test_bokeh_report.html
./Tests.4/0/cloudai_nccl_test_report.csv
./Tests.4/0/cloudai_nccl_test_bokeh_report.html
./Tests.2/0/cloudai_nccl_test_report.csv
./Tests.2/0/cloudai_nccl_test_bokeh_report.html
```
> Generate CSV reports in NCCL-tests

- src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py
Remove docstring from gen_exec_command in SleepStandaloneCommandGenStrategy to comply with docstring conventions.
Not needed.
> Remove docstring from gen_exec_command in SleepStandaloneCommandGenStrategy to comply with docstring conventions

- src/cloudai/_core/base_runner.py
- src/cloudai/_core/exceptions.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/runner/standalone/standalone_runner.py
- tests/test_job_submission_error.py
Enhance job submission error handling with custom exceptions
1. Added unit tests, and they are passing.
2. Tested on an internal server, and it prints error messages properly.
```
ERROR: Job Submission Failed
Test Name: Tests.1
Message: Failed to retrieve job ID from command output.
Command: 'sbatch ...'
stdout: ''
stderr: 'sbatch: error: Batch job submission failed: Requested node configuration is not available'
```
> Enhance job submission error handling with custom exceptions

- src/cloudai/_core/base_job.py
- src/cloudai/_core/base_runner.py
- src/cloudai/_core/runner.py
- src/cloudai/_core/test_template.py
Update docstring to comply with coding style and max column length
CI pipelines passing.
> Update docstring to comply with coding style and max column length

- pyproject.toml
Bump package version to v0.7. Otherwise it still reports itself as v0.6.
—
—
> Bump package version to v0.7

- src/cloudai/schema/system/slurm/slurm_system.py
- tests/test_slurm_system.py
Fix bug in parse_node_list to handle multiple node ranges correctly
Added a new test case, `("node-[055,114],node-[056,115]", ["node-055", "node-114", "node-056", "node-115"]),`. All test cases are passing.
> Fix bug in parse_node_list to handle multiple node ranges correctly

- src/cloudai/_core/test.py
Remove Optional for correct type annotation in test.py
CI pipelines are passing.
> Remove Optional for correct type annotation in test.py

- ci_tools/check_copyright_headers.py
- src/cloudai/_core/__init__.py
- src/cloudai/_core/registry.py
- src/cloudai/installer/__init__.py
- src/cloudai/runner/__init__.py
Fix ci_tools/check_copyright_headers.py and add missing copyright headers
CI pipelines passing.
> Fix ci_tools/check_copyright_headers.py and add missing copyright headers

- src/cloudai/__init__.py
- src/cloudai/_core/base_job.py
- src/cloudai/_core/base_runner.py
- src/cloudai/_core/exceptions.py
- src/cloudai/_core/job_status_result.py
- src/cloudai/_core/job_status_retrieval_strategy.py
- src/cloudai/_core/registry.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_template.py
- src/cloudai/_core/test_template_parser.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/runner/standalone/standalone_runner.py
- src/cloudai/schema/test_template/common/default_job_status_retrieval_strategy.py
- tests/test_registry.py
* This PR has been introduced to identify job completion status after each test.
* This PR introduces a new strategy called JobStatusRetrievalStrategy.
* By default, all tests use DefaultJobStatusRetrievalStrategy, which always returns True.
* If a job fails, the base runner identifies it and raises an exception. This PR also introduces JobFailureError for this purpose.
* CI pipelines passing.
* Tests were updated to accommodate the new strategy.
> Identify job completion status after each test

- src/cloudai/__init__.py
- src/cloudai/_core/base_job.py
- src/cloudai/_core/base_runner.py
- src/cloudai/_core/exceptions.py
- src/cloudai/_core/job_status_result.py
- src/cloudai/_core/job_status_retrieval_strategy.py
- src/cloudai/_core/registry.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_template.py
- src/cloudai/_core/test_template_parser.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/runner/standalone/standalone_runner.py
- src/cloudai/schema/test_template/common/default_job_status_retrieval_strategy.py
- src/cloudai/schema/test_template/nccl_test/job_status_retrieval_strategy.py
- tests/test_job_status_retrieval_strategy.py
- tests/test_registry.py
Implement NcclTestJobStatusRetrievalStrategy and add corresponding tests
1. Added the following tests.
* TestNcclTestJobStatusRetrievalStrategy
* test_no_stdout_file
* test_successful_job
* test_failed_job
2. Tested on a real system manually.
```
Test Scenario: nccl-test
Test Name: nccl_test_all_gather
Description: all_gather
Section Name: Tests.2
Test Name: nccl_test_all_reduce
Start Post Comp: Tests.1, Time: 0 seconds
Section Name: Tests.3
Test Name: nccl_test_reduce_scatter
Description: reduce_scatter
Start Post Comp: Tests.2, Time: 0 seconds
Section Name: Tests.4
Test Name: nccl_test_alltoall
Description: alltoall
Start Post Comp: Tests.3, Time: 0 seconds
[Kill Tests.1]
Job 260660 for test Tests.1 failed: Missing success …
```
> Implement NcclTestJobStatusRetrievalStrategy and add corresponding tests

- src/cloudai/_core/test_scenario_parser.py
Cast `num_nodes` to int in TestScenarioParser to ensure correct data type.
Error in `main`
```
...
Traceback (most recent call last):
...
sys.exit(main())
^^^^^^
File "/home/theo/cloudai/src/cloudai/__main__.py", line 229, in main
handle_dry_run_and_run(args)
File "/home/theo/cloudai/src/cloudai/__main__.py", line 179, in handle_dry_run_and_run
asyncio.run(runner.run())
File "/home/theo/miniconda3/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/home/theo/miniconda3/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/theo/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File …
```
> Cast `num_nodes` to int in TestScenarioParser to ensure correct data type

- tests/test_acceptance.py
In acceptance test, implement check of the numbers of directories executed during the dry run
Executed the test with good/bad values
> Check number of created directories in acceptance test

- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
Support empty queues in sinfo
Error before bugfix.
```
def parse_sinfo_output(self, sinfo_output: str, node_user_map: Dict[str, str]) -> None:
"""                                                                       
Parse the output from the 'sinfo' command to update node states.
Args:                
sinfo_output (str): The output from the sinfo command.
node_user_map (dict): A dictionary mapping node names to users.
"""                                                                       
for line in sinfo_output.split("\n")[1:]:  # Skip the header line
if not line.strip():                                                  
continue                                                          
parts = line.split()
>               partition, _, _, _, state, nodelist = parts[:6]
E …
```
> Support empty queues in sinfo

- requirements.txt
- src/cloudai/__main__.py
- src/cloudai/_core/base_installer.py
- src/cloudai/_core/install_status_result.py
- src/cloudai/_core/install_strategy.py
- src/cloudai/_core/test_template.py
- src/cloudai/installer/installer.py
- src/cloudai/installer/slurm_installer.py
- src/cloudai/installer/standalone_installer.py
- src/cloudai/parser/system_parser/slurm_system_parser.py
- src/cloudai/schema/test_template/chakra_replay/slurm_install_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_install_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_install_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- src/cloudai/schema/test_template/sleep/standalone_install_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_install_strategy.py
- src/cloudai/systems/slurm/slurm_system.py
- src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
- Introduced detailed error messages in the installation process.
- Added a new `DockerImageCacheManager` to reduce code duplication and manage Docker image caching.
- Enabled optional caching of Docker images locally.
- Passed error messages from the lower levels up to the installer and user.
- Updated various classes and methods to use the new `InstallStatusResult` for error handling.
- Modified `requirements.txt` to include `requests` library for handling Docker image checks.
- Added unit tests for the new functionality to ensure reliability and correctness.
Added unit tests.
> Enhance installation process with detailed error handling and Docker image caching

- src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
- tests/test_slurm_install_strategy.py
Pass install_path to SlurmInstallStrategy. Issue identified and fixed by @lappazos at https://github.com/NVIDIA/cloudai/pull/63
**1. Run on a real system.**
Before fix
```
$ cloudai --mode run --system_config_path conf/v0.6/general/system/... --test_scenario_path conf/v0.6/general/test_scenario/nccl_test.toml
Cloud AI has not been installed. Please run install mode first.
Some test templates are not installed.
NeMoLauncher: Not installed
```
After fix
```
$ cloudai --mode run --system_config_path conf/v0.6/general/system/... --test_scenario_path conf/v0.6/general/test_scenario/nccl_test.toml
Test Scenario: nccl-test
Test Name: nccl_test_all_reduce
```
**2. Unit tests**
Added test cases.
> Pass install_path to SlurmInstallStrategy

- src/cloudai/parser/system_parser/slurm_system_parser.py
- tests/test_slurm_system_parser.py
Ensure proper conversion of 'cache_docker_images_locally' to boolean
Added unit tests.
> Ensure proper conversion of 'cache_docker_images_locally' to boolean

- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
Ensure docker image URL has valid scheme in _check_docker_image_accessibility
Updated test cases to cover scenarios where the Docker image URL might have an invalid scheme, ensuring it is corrected and validated properly.
> Ensure docker image URL has valid scheme in _check_docker_image_accessibility

- src/cloudai/_core/base_installer.py
- tests/test_base_installer.py
The change ensures that the detailed return values are read and evaluated correctly during the installation and uninstallation processes. Previously, the return value was not checked, and the process relied on exceptions to indicate failure. By checking the return value, the code can now accurately determine whether to return success or failure based on the detailed results provided.
Added test cases and ran it on a real system.
> Updated BaseInstaller to correctly handle DockerImageCacheResult

- src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
This PR addresses two key issues in the `DockerImageCacheManager`:
1. **Handling Missing Subdirectories**:
- Updated the `cache_docker_image` method to create the necessary subdirectory if it does not exist. This ensures that the caching process does not fail due to missing subdirectories.
2. **Passing Partition Name Dynamically**:
- Updated the `DockerImageCacheManager` to accept a partition name during initialization and use it in the `enroot import` command. Removed the incorrect default partition keyword handling to improve command compatibility and functionality in various environments.
Additionally, the unit tests for `DockerImageCacheManager` have been updated to reflect these changes, including new test cases for the creation of missing subdirectories and the dynamic use of the …
> Handle missing subdirectories and pass partition name dynamically in DockerImageCacheManager

- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
DockerImageCacheManager is used in CloudAI to optionally cache Docker images. While it has been used in InstallStrategy, it was missing in CommandGenStrategy. This caused the commands generated by CommandGenStrategy to not properly reflect the caching option or path. This PR fixes the bug by integrating DockerImageCacheManager into CommandGenStrategy.
Tested on a real system manually.
**1. NCCL test**
```
2024-06-05 18:32:44,030 - INFO - Executing command for test Tests.1: sbatch ... cloudai_sbatch_script.sh
```
```
srun \
--mpi=pmix \
--container-image=[DOCKER URL] \
/usr/local/bin/all_reduce_perf_mpi \
--nthreads 1 \
--ngpus 1 \
--minbytes 128 \
--maxbytes 16G \
--stepbytes 1M \
--op sum \
--datatype float \
--root 0 \
--iters 100 \
--warmup_iters 50 \
--agg_iters 1 \
--average 1 \ …
```
> Use DockerImageCacheManager in CommandGenStrategy

- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- tests/test_slurm_install_strategy.py
This PR updates the _clone_repository method to properly handle cases where the repository path already exists. Previously, if the NeMo-Launcher repository directory was already present, the installation would fail due to the existing directory. The updated method now skips pulling the latest changes and directly checks out the specified commit, ensuring a smoother installation process.
**1. Add unit tests
2. Ran on a real system**
Before Bugfix
```
Some test templates failed to install.
- ChakraReplay: Success
- Sleep: Success
- NcclTest: Success
- UCCTest: Success
- NeMoLauncher: Failed to clone repository: fatal: destination path '/.../install/NeMo-Launcher/NeMo-Launcher' already exists and is not an empty directory.
```
After Bugfix
```
$ python ./cloudaix.py --mode install 
[Silently …
```
> Update `_clone_repository` to handle existing repository path

- src/cloudai/__main__.py
Currently, CloudAI checks the installation status of all available test templates before running any experiments. This check occurs in the "run" mode and can unnecessarily block the progress of users who are only interested in specific test templates.
Before this PR
```
$ cloudai --mode run --test_scenario_path ../nccl_test.toml 
CloudAI has not been installed. Please run install mode first.
Some test templates are not installed.
- NeMoLauncher: NeMo datasets are not installed on some nodes. Nodes without datasets:... This directory should contain all necessary datasets for NeMo Launcher to function properly.
```
After this PR
```
$ cloudai --mode run --test_scenario_path ../nccl_test.toml 
Test Scenario: nccl-test                     …
```
> Remove redundant installation check from run mode

- requirements.txt
- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
This pull request addresses a bug in the `_check_docker_image_accessibility` function. Previously, the function used the `requests` library to check Docker image accessibility, but this method was unreliable as it always returned `true`. The function has now been updated to use `enroot import` for a more accurate check.
**Changes:**
- Replaced `requests` library with `enroot import` to verify Docker image accessibility.
- The function now searches for specific keywords while running `enroot import` to determine if the Docker image is accessible.
- Opted against using the `docker` package as it requires Docker permissions, which may not always be guaranteed.
**1. Added unit tests
2. Tested on a real system**
```
$ python ./cloudaix.py --mode install ...
[installed]
```
> Fix bug in `_check_docker_image_accessibility`

- src/cloudai/__main__.py
- src/cloudai/_core/base_installer.py
- src/cloudai/_core/base_runner.py
- src/cloudai/_core/grader.py
- src/cloudai/_core/parser.py
- src/cloudai/_core/runner.py
- src/cloudai/_core/test_scenario.py
- src/cloudai/_core/test_template.py
- src/cloudai/_core/test_template_parser.py
- src/cloudai/installer/installer.py
- src/cloudai/installer/slurm_installer.py
- src/cloudai/report_generator/report_generator.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/runner/standalone/standalone_runner.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- src/cloudai/systems/slurm/slurm_system.py
- src/cloudai/util/docker_image_cache_manager.py
- tests/test_acceptance.py
- tests/test_docker_image_cache_manager.py
1. Use `logging.config`, always write `DEBUG` logs into debug file.
2. Use module-level `logger` object for better configurability on user end.
3. Use explicit arguments instead of `argparse`'s args for high level function. It will simplify code re-use for users.
CI
—
> Use logging.config and do not pass CLI args as a parameter

- README.md
- src/cloudai/__init__.py
- src/cloudai/__main__.py
- src/cloudai/_core/base_installer.py
- src/cloudai/_core/base_multi_file_parser.py
- src/cloudai/_core/parser.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_parser.py
- src/cloudai/_core/test_template_parser.py
- src/cloudai/installer/installer.py
- src/cloudai/installer/slurm_installer.py
- tests/test_acceptance.py
- tests/test_base_installer.py
- tests/test_parser.py
1. Update CLI args to highlight where we need a directory or just a file. Replaced underscores with dashes as it seems to be nowadays' standard.
2. Use `TestScenario` for filtering tests and test templates used for installation.
CI
—
> New CLI args and filter tests templates for installation

- pyproject.toml
- src/cloudai/report_generator/tool/tensorboard_data_reader.py
1. `tbparse` import takes long time, made it a lazy import. This improves the very basic operations like showing help. On my host time reduced from 3 to 1 sec.
2. Added [`ERA`](https://docs.astral.sh/ruff/rules/#eradicate-era) linter to report commented code.
CI
—
> Improve overall performance

- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
Fix _check_docker_image_accessibility condition and add detailed logging
**1. CI pipelines pass
2. Ran on a real system**
```
$ python ./cloudaix.py --mode install --system-config ... --log-level DEBUG
[INFO] Docker image cached successfully at ...
[INFO] Installation successful.
```
> Fix _check_docker_image_accessibility condition and add detailed logging

- src/cloudai/__main__.py
- src/cloudai/_core/base_installer.py
- src/cloudai/installer/installer.py
- src/cloudai/installer/slurm_installer.py
- tests/test_acceptance.py
- tests/test_base_installer.py
Refactor installer for TestTemplate iterables in Slurm and base classes. Currently, all tests in a test scenario directory are passed to `is_installed`, `install`, and `uninstall`, which is inefficient. This approach triggers multiple processes for installation and uninstallation. This pull request now uniquely identifies test templates within the directory before passing them to the respective methods.
**1. CI passes.
2. Ran on a system**
```
$ python ./cloudaix.py --mode install --system-config ...
[INFO] Scheduler: slurm                                                     
[INFO] Checking installation status of components.                          
[INFO] Verifying installation status of test templates.                     
[INFO] Test template NcclTest is not installed.
[INFO] Not all …
```
> Refactor handle_install_and_uninstall to identify unique test templates

- src/cloudai/__main__.py
- src/cloudai/_core/base_installer.py
- src/cloudai/installer/installer.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
Reduce stdout logging by default, track only main progress and errors. Keep all details in the file by default.
```bash
$ cloudai --mode install --system-config system.toml --test-templates-dir test_template/ --tests-dir test/
[INFO] System configuration file: ...
[INFO] Test templates directory: ...
[INFO] Tests directory: ...
[INFO] Test scenario file: None
[WARNING] No JobIdRetrievalStrategy found for TestTemplateParser and SlurmSystem
[WARNING] No JobStatusRetrievalStrategy found for TestTemplateParser and SlurmSystem
[INFO] System Name: ...
[INFO] Not all components are ready
[INFO] Installing test templates.
[INFO] 1/5 Installation for ChakraReplay finished with status: OK
[INFO] 2/5 Installation for Sleep finished with status: …
```
> Reduce logs for stdout

- src/cloudai/schema/test_template/nemo_launcher/report_generation_strategy.py
Fix bug in NeMo launcher report generation. The tag name has been updated from 'train_step_timing' to 'train_step_timing in s'
```
$ python3 cloudaix.py --system-config ... --output-dir ... --mode generate-report --test-scenario ...
```
[Report Generated]
> Fix bug in NeMo launcher report generation

- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- tests/test_slurm_install_strategy.py
Add pip install requirements.txt step to NeMoLauncherSlurmInstallStrategy
```
ModuleNotFoundError: No module named 'hydra''
ModuleNotFoundError: No module named 'tqdm''
ModuleNotFoundError: No module named 'zstandard''
```
**1. CI passes**
**2. Ran on a real system**
```
$ pip list | grep hydra
hydra-core              1.2.0
$ pip uninstall hydra-core
$ python ./cloudaix.py --mode install --system-config ...
[INFO] Not all components are ready
[INFO] Installing test templates.
...
[INFO] 5/5 Installation for NeMoLauncher finished with status: OK
[INFO] Installation successful.
$ pip list | grep hydra
hydra-core              1.2.0
```
> Add pip install requirements.txt step to NeMoLauncherSlurmInstallStrategy

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Fix the bug in generating the NeMo launcher command. Daria encountered the error "FileNotFoundError: [Errno 2] No such file or directory: .../run/results/nemo_log_globalrank-127_localrank-7.txt" in log-nemo-megatron-run_*.err. I found that the keyword venv/bin/python was causing the issue. The intention was to call venv/bin/python to run Python in the virtual environment, not the global Python. Directly calling Python fixed the issue, as it could identify the correct Python binary anyway.
```
$ python ./cloudaix.py --mode run --system-config conf/v0.6/general/system/... --test-templates-dir conf/v0.6/general/test_template/ --tests-dir conf/v0.6/general/test/ --test-scenario conf/v0.6/general/test_scenario/gpt/gpt.toml
...
[INFO] Job completed: Tests.1
[INFO] All test scenario results …
```
> Fix bug in generating NeMo launcher command

- USER_GUIDE.md
Add `cache_docker_images_locally` field to system schema in USER_GUIDE.md
Not needed.
> Add `cache_docker_images_locally` field to system schema in USER_GUIDE.md

- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_install_strategy.py
Allow local docker image caching for JaxToolbox
```
$ python ./cloudaix.py --mode run --system-config conf/v0.6/general/system/... --log-level DEBUG
--test-templates-dir conf/internal/jax_toolbox/test_template/ --tests-dir conf/internal/jax_toolbox/test --test-scenario conf/internal/jax_toolbox/test_scenario/grok_proxy/test_scenario_...toml     
[INFO] All test scenario results stored at:...
[INFO] All test scenario execution attempts are complete. Please review the 'debug.log' file to confirm successful completion or to identify any issues.                                                                    
```
> Allow local docker image caching for JaxToolbox

- USER_GUIDE.md
- conf/system/example_slurm_cluster.toml
- src/cloudai/parser/system_parser/slurm_system_parser.py
- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/slurm_system.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_system_parser.py
Add mpi field to SlurmSystem and allow different MPI options in schema
1. Added unit tests for SlurmSystemParser
2. Ran CloudAI with the dry-run mode
Chakra Replay
```
$ python cloudaix.py --mode dry-run --system-config conf/v0.6/general/system/... --test-scenario conf/v0.6/general/test_scenario/chakra_replay.toml                          
```
```
srun \
--mpi=pmi2 \
...
```
NCCL Test
```
$ python cloudaix.py --mode dry-run --system-config conf/v0.6/general/system/... --test-scenario conf/v0.6/general/test_scenario/nccl_test.toml                 
```
```
srun \
--mpi=pmi2 \
...
```
UCC Test
```
$ python cloudaix.py --mode dry-run --system-config conf/v0.6/general/system/... --test-scenario conf/v0.6/general/test_scenario/ucc_test.toml                 
```
```
srun \
--mpi=pmi2 \
...
```
> Add mpi field to SlurmSystem and allow different MPI options in schema

- src/cloudai/__main__.py
- tests/test_acceptance.py
Update logging to use dynamic log file name from args.log_file in run mode
1. Updated unit tests, and CI pipelines pass
2. Ran it on my laptop
```
$ cloudai --mode run --system-config conf/system/standalone_system.toml --test-scenario conf/test_scenario/sleep.toml --test-templates-dir conf/test_template --tests-dir conf/test
[INFO] System configuration file: conf/system/standalone_system.toml
[INFO] Test templates directory: conf/test_template
[INFO] Tests directory: conf/test
[INFO] Test scenario file: conf/test_scenario/sleep.toml
...
[INFO] Job completed: Tests.2
[INFO] Job completed: Tests.4
[INFO] Job completed: Tests.3
[INFO] All test scenario results stored at: /Users/theo/cloudai/results/test_scenario_example_2024-07-09_07-24-57
...
[INFO] All test …
```
> Update logging to use dynamic log file name from args.log_file in run mode

- src/cloudai/__init__.py
- src/cloudai/schema/test_template/sleep/__init__.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- tests/test_init.py
Add support for Sleep on Slurm systems
The main branch fails with the following error.
```
$ cloudai --mode run --system-config conf/v0.6/general/system/system_1.toml --test-scenario conf/v0.6/general/test_scenario/sleep.toml --tests-dir conf/v0.6/general/test/ --test-templates-dir conf/v0.6/general/test_template/
[INFO] System configuration file: conf/v0.6/general/system/system_1.toml
[INFO] Test templates directory: conf/v0.6/general/test_template
[INFO] Tests directory: conf/v0.6/general/test
[INFO] Test scenario file: conf/v0.6/general/test_scenario/sleep.toml
[WARNING] No JobIdRetrievalStrategy found for TestTemplateParser and SlurmSystem
[WARNING] No JobStatusRetrievalStrategy found for TestTemplateParser and SlurmSystem
[INFO] System Name: system_1 …
```
> Add support for Sleep on Slurm systems

- src/cloudai/_core/test_template.py
Raise descriptive exceptions when strategies are missing
```
$ python ./cloudaix.py --mode run --system-config conf/v0.6/general/system/[SYSTEM_1].toml --test-templates-dir conf/v0.6/general/test_template --tests-dir conf/v0.6/general/test --test-scenario conf/v0.6/general/test_scenario/sleep.toml 
[INFO] System configuration file: conf/v0.6/general/system/[SYSTEM_1].toml
[INFO] Test templates directory: conf/v0.6/general/test_template
[INFO] Tests directory: conf/v0.6/general/test
[INFO] Test scenario file: conf/v0.6/general/test_scenario/sleep.toml
[WARNING] No JobIdRetrievalStrategy found for TestTemplateParser and SlurmSystem
[WARNING] No JobStatusRetrievalStrategy found for TestTemplateParser and SlurmSystem
[INFO] System Name: [SYSTEM_1]
[INFO] …
```
> Raise descriptive exceptions when strategies are missing

- pyproject.toml
- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
Updated `SlurmCommandGenStrategy` implementation:
1. Renamed `_generate_srun_command` to `generate_full_srun_command`.
2. Added two new functions to be called as part of it: `generate_srun_command` and `generate_test_command`.
3. Use `self.slurm_system.mpi` directly instead of of extra `slurm_args`.
1. CI
2. Ran the following test templates with the dry-run mode and compared the generated command and sbatch script between the main branch and the am/slurm-common branch
* Sleep (success)
* NcclTest (success)
* UccTest (success)
* JaxToolbox (success)
* NeMoLauncher (success)
—
> Move parts of srun CLI generation into base class

- src/cloudai/schema/test_template/jax_toolbox/report_generation_strategy.py
Add warning for insufficient epochs in JaxToolbox report generation. Proposed by Srivatsan Krishna.
CI passes
> Add warning for insufficient epochs in JaxToolbox report generation

- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/template.py
Remove subtest name check in NcclTestSlurmCommandGenStrategy. CloudAI will check the subtest name field to ensure the value is within the predefined values in the test template schema. Therefore, the values do not need to be kept in the schema. This will allow CloudAI to support bisection_perf_mpi as well. This idea was proposed by Eyal Chocron.
CI passes
> Remove subtest name check in NcclTestSlurmCommandGenStrategy

- src/cloudai/parser/system_parser/slurm_system_parser.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/slurm_system.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
Allow extra `srun` args set in system config.
CI
—
> Allow extra srun args set in system config

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
This PR is based on andrei's : https://github.com/NVIDIA/cloudai/pull/160
It enables reservation flag to be transmitted to NeMoLauncher
system.toml
```
extra_srun_args = "--reservation my-reservation"
``` 
command 
```
$ python ./cloudaix.py --mode run --system-config ... --test-templates-dir conf/v0.6/general/test_template --tests-dir conf/v0.6/general/test --test-scenario conf/v0.6/general/test_scenario/llama/llama3_70B.toml
...
Test Name: llama3_70B
Description: llama
[INFO] Initializing Runner
...
```
> add support for NeMo Launcher in the reservation

- src/cloudai/_core/base_runner.py
- src/cloudai/_core/test_scenario.py
- src/cloudai/_core/test_scenario_parser.py
Add the job_status_check flag to the test scenario schema to ignore checking the job status. The flag is applied globally. Currently, if a test is killed or fails in the middle and does not produce a proper result, it is considered a job failure by the status-checking logic. As a result, all tests are terminated, and reports are not generated. This PR introduces a new flag, job_status_check, to the test scenario schema so that users can optionally enable or disable the job status check. By default, it is set to True, and it can be set to False if users wish. The flag is applied to all tests in the test scenario; you cannot optionally turn the check on or off for each test individually.
example_test.toml
```
name = "nccl-test"
job_status_check = false
[Tests.1]
name = …
```
> Add job_status_check flag to disable checks for specific tests

- src/cloudai/util/docker_image_cache_manager.py
Defer docker image URL accessibility check to srun when not caching locally. This PR is created to fix a bug reported by @srivatsankrishnan. CloudAI has an install mode to install test templates. In the install stage, docker images are cached locally when a user sets cache_docker_images_locally to true. Even if cache_docker_images_locally is set to false, the accessibility of the given docker image URL is tested. The problem arises when the head node does not have enroot. In install mode, CloudAI calls DockerImageCacheManager's `check_docker_image_exists`. `check_docker_image_exists` uses enroot, and when the head node does not have enroot, it fails to check and then reports an unknown error as shown below.
```
[ERROR] Accessibility check failed for Docker image URL: .... Error: Failed to …
```
> Defer docker image URL accessibility check to srun when not caching locally

- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
The reservation feature was only working with NeMoLauncher. Now it works also for nccl tests
system.toml
extra_srun_args = "--reservation my-reservation"
command
$ python ./cloudaix.py --mode run --system-config ... --test-templates-dir conf/v0.6/general/test_template --tests-dir conf/v0.6/general/test --test-scenario conf/v0.6/general/test_scenario/nccl_test_all_to_all.toml ...
Test Name: nccl_test_alltoall
Description: alltoall
[INFO] Initializing Runner
...
> Add the reservation feature to all tests

- conf/common/system/kubernetes_cluster.toml
- requirements.txt
- src/cloudai/__init__.py
- src/cloudai/_core/json_gen_strategy.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_template.py
- src/cloudai/_core/test_template_parser.py
- src/cloudai/installer/kubernetes_installer.py
- src/cloudai/parser/system_parser/kubernetes_system_parser.py
- src/cloudai/runner/kubernetes/__init__.py
- src/cloudai/runner/kubernetes/kubernetes_job.py
- src/cloudai/runner/kubernetes/kubernetes_runner.py
- src/cloudai/schema/test_template/sleep/__init__.py
- src/cloudai/schema/test_template/sleep/kubernetes_install_strategy.py
- src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
- src/cloudai/systems/kubernetes/__init__.py
- src/cloudai/systems/kubernetes/kubernetes_system.py
- tests/test_init.py
- Added Kubernetes support with KubernetesSystem, KubernetesJob, and KubernetesRunner classes.
- Implemented JsonGenStrategy for generating Kubernetes job specs, including SleepKubernetesJsonGenStrategy.
- Introduced KubernetesInstaller for managing Kubernetes installations.
- Updated Registry and Tests to include Kubernetes-specific components.
This PR builds upon @wpeng102's work in [PR #165](https://github.com/NVIDIA/cloudai/pull/165).
* Install
```
$ cloudai --mode install --system-config conf/system/kubernetes_cluster.toml --test-templates-dir conf/test_template --tests-dir conf/test/  --test-scenario conf/test_scenario/nccl_test.toml
[INFO] System configuration file: conf/system/kubernetes_cluster.toml
[INFO] Test templates directory: conf/test_template
[INFO] Tests directory: …
```
> Add Kubernetes Support

- pyproject.toml
- tests/test_package.py
1. Without it, `kubernetes` package is missing after installation.
2. Added a test to make sure `requirements.txt` and `pyproject.toml` are aligned for dependencies list.
CI
—
> Add missing k8s package into package dependencies.

- README.md
README.md incorrectly refers to `tests` instead of `test` directory. 
Fixing [issue](https://redmine.mellanox.com/issues/4050782) reported by Dmitry Kuzmin. 
CI
> Fix test directory name typo in README.md

- src/cloudai/__init__.py
- tests/test_init.py
Fix bug in generating NCCL test reports on K8s
> Fix bug in generating NCCL test reports on K8s

- src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
Use Host Network for Kubernetes NCCL Tests
https://github.com/Mellanox/cloudaix/pull/43
> Use Host Network for Kubernetes NCCL Tests

- .github/workflows/ci.yml
Extend CI for high level use cases
1. Local installation, both editable and default.
2. Run `--mode verify-systems`
3. Run `--mode verify-tests`
CI
—
> Extend CI for high level use cases

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Replace the 'training.values' key with 'training' in final_cmd_args​. In the NeMo launcher, the model to run should be passed to 'training,' not 'training.values.' CloudAI has to rely on an arbitrary key called 'values' because Pydantic and TOML do not allow having a value and nested arguments simultaneously.
1. CI passes
2. Ran on a server - Confirmed that the training arg has a correct value.
> Replace 'training.values' Key with 'training' in final_cmd_args

- src/cloudai/_core/test_template_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_install_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_install_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_install_strategy.py
Use system install path instead of local member variables.
CI passes
> Use System Install Path Instead of Local Member Variables

- src/cloudai/_core/command_gen_strategy.py
- src/cloudai/_core/json_gen_strategy.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_parser.py
- src/cloudai/_core/test_scenario_parser.py
- src/cloudai/_core/test_template.py
- src/cloudai/_core/test_template_strategy.py
- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
- tests/test_slurm_command_gen_strategy.py
- tests/test_slurm_install_strategy.py
Remove unused env_vars from the initialization code.
env_vars for test templates and their strategies are initialized in the test parser class, as shown below:
```
def _parse_data(self, data: Dict[str, Any]) -> Test:
test_def = self.load_test_definition(data)
env_vars = {}  # this field doesn't exist in Test or TestTemplate TOMLs
...
test_template_name = data.get("test_template_name", "")
test_template = self._get_test_template(test_template_name, env_vars, cmd_args)
...
return Test(
name=test_def.name,
description=data.get("description", ""),
test_template=test_template,
env_vars=env_vars,
cmd_args=cmd_args,
extra_env_vars=extra_env_vars,
extra_cmd_args=extra_cmd_args,
)
```
As you can see, env_vars is empty by default. Therefore, there is no need to pass env_vars initially. This PR …
> Remove Unused env_vars From Initialization Code

- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
This PR addresses a bug introduced by [PR #202](https://github.com/NVIDIA/cloudai/pull/202). In that PR, we aimed to retrieve the absolute path of the cached docker image because, on some servers, srun only worked with absolute paths. However, we found that remote URLs were also being incorrectly converted to absolute paths, and this PR resolves that issue. The bug was reported by Max, and I have fixed it. Additionally, I added a test case to cover docker images from remote URLs without local caching.
1. CI passes
2. Tested on a server and ran an NCCL test with a remote URL.
> Fix Bug in DockerImageCacheResult to Correctly Retrieve Absolute Paths

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
Add support for cluster account and gpus_per_node in Slurm command generation
1. CI passes
2. Ran it on a real system and observed the expected error message. Did not get a chance to run it to completion because the data directory is not yet available.
> Add Support for Cluster Account and gpus_per_node in Command Generation

- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- tests/test_slurm_install_strategy.py
NemoLauncher currently has three dependencies during `cloudai mode=install`. 
1. Dataset
2. Nemo-Launcher Repo
3. Nemo container
While the IL-1 has a dedicated raid server where the dataset is hosted, still users cannot install NemoLauncher (including container and the GitHub repo) on other clusters such as CW/EoS. Even in IL-1, @TaekyungHeo recently has filed a ticket to open Nemo framework has support for Mock datasets and dataset should not be a pre-condition for installing the Nemo launcher and its associated docker container. This PR removes the dataset installation dependencies from the SlurmInstallationStratergy.
CI/CD
Tested on CW
> Disabling dataset check during Nemo launcher installation

- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
Remove dead code by eliminating the unused install_path variable. If the variable had been used, ruff would have detected it.
CI passes.
> Remove Dead Code by Eliminating Unused `install_path`

- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
Remove unnecessary permission checks and exception handling in NeMoLauncherSlurmInstallStrategy. When the path does not exist or permission is insufficient, other APIs will raise exceptions, and these exceptions will be propagated accordingly. There is no reason to check these edge cases manually if there are no additional benefits.
CI passes
> Remove unnecessary permission checks and exception handling in NeMoLauncherSlurmInstallStrategy

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
CloudAI team found that absolute paths should be passed to NeMo launcher arguments. Otherwise, there can be an error because a Slurm system may not allow relative paths in container-mounts.
1. CI passes
2. [Ran on a server](https://github.com/Mellanox/cloudaix/pull/54)
> Use absolute paths in NeMo launcher

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
It is essential to support removing keys. Hydra allows users to remove keys with `~`, and it should be supported. Once `~` is found in the value, the key is removed. This is necessary for some test scenarios.
* CI passes. Added a unit test.
* It works on a server with additional commits as shown at [here](https://github.com/Mellanox/cloudaix/pull/54)
> Unset argument in NeMo launcher when its value is ~

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/test_definitions/nemo_launcher.py
- tests/test_slurm_command_gen_strategy.py
* **Use mock data by default in NeMo**: Set data_prefix to "[]", data_impl to "mock", "data_dir" to "~".
* **Validate NeMo launcher arguments**: Check data_dir and data_prefix only when data_impl is not mock
* **Make ruff happy**: Refactor NeMoLauncherSlurmCommandGenStrategy to lower the complexity of gen_exec_command.
* **Remove data_dir argument when data_impl==mock**
1. CI passes
2. [Ran on a server.](https://github.com/Mellanox/cloudaix/pull/54)
> Use mock data by default in NeMo launcher

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/test_definitions/nemo_launcher.py
- tests/test_slurm_command_gen_strategy.py
The current Nemo launcher in CloudAI generates the command and writes out the command in stdout. This PR logs the generated command into a readable bash script. This is consistent with how other frameworks implement the command generation logic in CloudAI.
CI/CD- Added two new unit tests 
Tested on CW.
```
(venv) srivatsank@cw-dfw-cs-001-dc-01:/lustre/fsw/portfolios/coreai/users/srivatsank/workspace/dev/cloudaix$ python cloudaix.py --mode run --system-config conf/common/system/coreweave.toml  --tests-dir conf/staging/gca_e2e/test --test-scenario conf/staging/gca_e2e/test_scenario/nemo_proxy/test_scenario_cw.toml                                                                                          
/lustre/fsw/portfolios/coreai/users/srivatsank/workspace/dev/cloudaix/venv/lib/python3.10/ …
```
> Generate Bash script during Nemo Launcher

- src/cloudai/_core/base_runner.py
- src/cloudai/_core/test.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/runner/standalone/standalone_runner.py
- tests/test_job_submission_error.py
The Test class has two methods, get_job_id and get_job_status, but these functions merely call the same methods from the TestTemplate class, which is unnecessary. This PR removes the redundant indirections.
CI passes
> Remove unnecessary indirections

- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
* Renamed generate_srun_command to generate_srun_prefix to better reflect its role
* Removed unused args in generate_srun_prefix
* Renamed generate_full_srun_command to generate_srun_command
CI passes
> Refactor SlurmCommandGenStrategy

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
- tests/test_slurm_install_strategy.py
Create a virtual environment and run NeMo Launcher inside it.
Before that Cloud AI env was used and some dependencies might either conflict raising a warning or fail to install causing installation error.
1. CI.
2. Manual run of installation.
3. Work with verification team to test it in the environment where installation error appeared first.
—
> Use venv for nemo launcher

- src/cloudai/_core/base_job.py
- src/cloudai/_core/command_gen_strategy.py
- src/cloudai/_core/json_gen_strategy.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_scenario.py
- src/cloudai/_core/test_template.py
- src/cloudai/runner/kubernetes/kubernetes_job.py
- src/cloudai/runner/kubernetes/kubernetes_runner.py
- src/cloudai/runner/slurm/slurm_job.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/runner/standalone/standalone_job.py
- src/cloudai/runner/standalone/standalone_runner.py
- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
- tests/test_standalone_system.py
Currently, CloudAI passes a very long list of arguments to `gen_exec_command` and `gen_json`. This PR proposes passing only the `TestRun` object to these methods. `TestRun` is a class that represents an instance of a test with run-specific arguments and configurations, such as the number of nodes and their list. Moreover, since `TestRun` has access to the original `Test` class, CloudAI no longer needs to pass arguments individually. Passing `TestRun` should suffice.
1. CI passes
```
$ python ./cloudaix.py --mode run --system-config ... --tests-dir conf/common/test --test-scenario conf/common/test_scenario/gpt/gpt_175B.toml 
[INFO] Test Scenario Name: gpt_175B
[INFO] Test Scenario: gpt_175B
Section …
```
> Pass TestRun to gen_exec_command and gen_json

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Bug fix for incorrect py_bin in NeMoLauncher. Introduced by https://github.com/NVIDIA/cloudai/pull/230.
Tested on an NVIDIA-internal server.
```
$ python ./cloudaix.py --mode run --system-config ... --tests-dir conf/common/test --test-scenario conf/common/test_scenario/gpt/gpt_175B.toml 
...
[INFO] Job completed: Tests.1
[INFO] All test scenario results stored at: results/gpt_175B_2024-10-07_07-33-45
```
> Bug fix for incorrect py_bin in NeMoLauncher

- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
srun commands are generated by `generate_srun_command`, which internally calls `generate_srun_prefix` and `generate_test_command`. Therefore, unless a test template requires something specific, any test template should update `generate_test_command` by default, not `generate_srun_command`.
CI passes
> Update Sleep to ensure implementation consistency

- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
Remove duplicated _format_env_vars calls. The _format_env_vars function is called in every test template's gen_exec_command, which is redundant. This PR eliminates the function calls within each template and moves the _format_env_vars call to the parent class.
CI passes
> Remove duplicated _format_env_vars calls

- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_command_gen_strategy.py
The `generate_test_command` function is intended to generate the core command used in an `srun` command. As a result, it does not need to accept `slurm_args`, which should be managed by a prefix-generating function. This PR removes `slurm_args` from the argument list.
CI passes
> Remove unnecessary arg from generate_test_command

- src/cloudai/_core/grader.py
- src/cloudai/_core/test.py
- src/cloudai/_core/test_scenario.py
- src/cloudai/_core/test_scenario_parser.py
- src/cloudai/report_generator/report_generator.py
- tests/test_test_scenario.py
Move more fields from `Test` to `TestRun`. This is to unblock `Test` and `TestDefinition` merging under single object to avoid confusion.
CI
—
> Move more fields from Test to TestRun

- src/cloudai/__main__.py
- tests/test_acceptance.py
It happened when two tests based on the same TestTemplate class, but with different test_template_name started caching the same image into the same location.
1. CI
2. Follow reproducing steps from the internal bug.
—
> Fix race condition during docker images caching

- tests/slurm_command_gen_strategy/test_chakra_replay.py
- tests/slurm_command_gen_strategy/test_nccl.py
- tests/slurm_command_gen_strategy/test_sleep.py
- tests/slurm_command_gen_strategy/test_ucc.py
Add unit tests for SlurmCommandGenStrategy
CI passes
> Add unit tests for SlurmCommandGenStrategy

- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
Fix missing 'output_path' in cmd_args.
1. CI
2. Manual run
—
> Fix missing 'output_path' in cmd_args

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/test_definitions/nemo_launcher.py
- tests/slurm_command_gen_strategy/test_nemo_launcher.py
This is a bug fix for https://redmine.mellanox.com/issues/4111103. Previously, we introduced https://github.com/NVIDIA/cloudai/pull/223 to allow users to remove keys from the argument list when not needed. However, it turns out that we cannot apply this approach to the data_dir argument. Therefore, this PR removes the feature, and any arguments that should be excluded by default should not be added to the test definition. Instead, they should be included in the extra_cmd_args section when necessary.
1. CI passes.
> Remove assigning null when the value is null (NeMo launcher)

- src/cloudai/cli/handlers.py
- src/cloudai/parser.py
1. Verify all configs, not just till first failure.
2. Improve errors reporting.
1. CI.
2. Manual run for different modes and check output.
Example output:
```bash
cloudai verify-systems conf/common/system
[INFO] Verifying conf/common/system/standalone_system.toml...
[INFO] Verifying conf/common/system/example_slurm_cluster.toml...
[ERROR] Failed to parse system definition: conf/common/system/example_slurm_cluster.toml
[ERROR] Field 'install_path': Field required
[INFO] Verifying conf/common/system/kubernetes_cluster.toml...
[ERROR] Failed to parse system definition: conf/common/system/kubernetes_cluster.toml
[ERROR] Field 'install_path': Field required
[ERROR] 2 out of 3 system configurations have issues.
```
> Improve verify modes

- src/cloudai/systems/slurm/slurm_system.py
- tests/conftest.py
- tests/test_slurm_system.py
This is a bug fix for https://redmine.mellanox.com/issues/4100971.
* Handle node allocation errors gracefully, log details, and exit on failure
* Enhance exception message in allocate_nodes
CI passes.
> Handle node allocation errors gracefully, log details, and exit on failure

- src/cloudai/test_definitions/nemo_launcher.py
Bug fix for [this issue](https://redmine.mellanox.com/issues/4107571). The problem is due to missing LLAMA3 configuration files, as reported by Arik Gelman. The bug was introduced by [this PR](https://github.com/NVIDIA/cloudai/pull/145). We should have used the commit hash 599ecfcbbd64fd2de02f2cc093b1610d73854022, but we are currently using cf411a9ede3b466677df8ee672bcc6c396e71e1a. You can see [here](https://github.com/NVIDIA/cloudai/blob/854e06f6487af364f93e29e606c9960a38899829/conf/common/test_template/nemo_launcher.toml#L26) that we used 599ecfcbbd64fd2de02f2cc093b1610d73854022 before this PR. The [commit hash](https://github.com/NVIDIA/NeMo-Framework-Launcher/tree/599ecfcbbd64fd2de02f2cc093b1610d73854022/launcher_scripts/conf/training/llama) has the required configuration files, such …
> Update NeMo launcher commit hash and image tag

- src/cloudai/test_definitions/grok.py
- tests/slurm_command_gen_strategy/test_jax_toolbox.py
This is a bug fix for https://redmine.mellanox.com/issues/4125377. The `output_path` is updated in the `gen_exec_command` of `JaxToolboxSlurmCommandGenStrategy`, but it was eventually flattened to `{test_name}.output_path`, which caused the bug. This PR resolves the issue.
1. CI passes. Added new unit tests
2. The following command works now
```
$ python ./cloudaix.py --log-level DEBUG --log-file dry-run_jax_grok.log dry-run --system-config ... --tests-dir conf/devops/verification/test/ --test-scenario ...
```
>  Fix bugs in updating the output_path of JaxToolbox cmd_args

- README.md
- USER_GUIDE.md
- src/cloudai/cli/cli.py
- src/cloudai/cli/handlers.py
- tests/test_cli.py
Bug fix for https://redmine.mellanox.com/issues/4125866. 
1. CI passes
```
(test4) theo@login-eos02:~/cloudaix-main$ rm results/nccl-test_2024-10-21_05-58-17/Tests.1/0/cloudai_nccl_test_bokeh_report.html
(test4) theo@login-eos02:~/cloudaix-main$ rm results/nccl-test_2024-10-21_05-58-17/Tests.1/0/cloudai_nccl_test_csv_report.csv 
(test4) theo@login-eos02:~/cloudaix-main$ python ./cloudaix.py generate-report --system-config /home/theo/cloudaix-main/conf/common/system/eos.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nccl_test.toml --results-dir results/nccl-test_2024-10-21_05-58-17/
/home/theo/scratch/miniconda3/envs/test4/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.20) or chardet …
```
> Rename --output-dir to --results-dir for generate-report command

- USER_GUIDE.md
- conf/common/test_scenario/nccl_test.toml
- conf/common/test_scenario/nemo_launcher.toml
- conf/common/test_scenario/nemo_launcher_with_noise.toml
- conf/common/test_scenario/sleep.toml
- conf/common/test_scenario/ucc_test.toml
- conf/release/spcx/l40s/test_scenario/l40s_bc_nccl_test.toml
- src/cloudai/_core/base_runner.py
- src/cloudai/_core/test_scenario.py
- src/cloudai/_core/test_scenario_parser.py
- tests/test_test_scenario.py
As we can't guarantee this delay, we are removing it to avoid confusion.
CI.
—
> Remove delay support in dependencies

- tests/job_status_retrieval_strategy/test_jax_toolbox_job_status_retrieval_strategy.py
- tests/job_status_retrieval_strategy/test_nccl_job_status_retrieval_strategy.py
Split `tests/test_job_status_retrieval_strategy.py` to `tests/job_status_retrieval_strategy/test_jax_toolbox_job_status_retrieval_strategy.py` and `tests/job_status_retrieval_strategy/test_nccl_job_status_retrieval_strategy.py` for maintainability.
CI passes
> Refactor JobStatusRetrievalStrategy unit tests

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Bug fix for https://redmine.mellanox.com/issues/4128871.
1. CI passes
num_nodes
```
#!/bin/bash
#SBATCH --account=coreai_dlalgo_ci
#SBATCH --error=/home/theo/cloudaix-main/results/llama3_70b_16N_LONG_RUN_2024-10-23_03-33-39/Tests.1/0/run/log-coreai_dlalgo_ci-cloudai.nemo:run_%j.err
#SBATCH --exclusive
#SBATCH --job-name=coreai_dlalgo_ci-cloudai.nemo:run
#SBATCH --mem=0
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=8
#SBATCH --output=/home/theo/cloudaix-main/results/llama3_70b_16N_LONG_RUN_2024-10-23_03-33-39/Tests.1/0/run/log-coreai_dlalgo_ci-cloudai.nemo:run_%j.out
#SBATCH --partition=batch
#SBATCH --time=96:00:00
export NCCL_IB_TIMEOUT=20
export TRANSFORMERS_OFFLINE=0
export TORCH_NCCL_AVOID_RECORD_STREAMS=1
export NCCL_NVLS_ENABLE=0
export …
```
> Fix bug by removing trailing newline from +cluster.nodelist in command args

- src/cloudai/_core/test_scenario_parser.py
* Rename testruns_by_id to test_runs_by_id
* Rename `_create_section_test_run` to `_create_test_run`. The concept of "section test" is deprecated and has been replaced by "test run". There is no concept of a "section test run".
CI passes
> Rename TestRun-related var and method in src/cloudai/_core/test_scenario_parser.py

- src/cloudai/_core/base_runner.py
We don't know the root cause of the issue, but it seems to be related to removed delays in some configurations.
CI.
—
> Always delay job submission to avoid double-booking in slurm

- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/test_definitions/chakra_replay.py
- tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
Chakra replay has been renovated by Sanshan, Songyan, and Taekyung. This PR updates Chakra replay so that it can use the latest Chakra replay
1. CI passes
2. Ran on a real system: /auto/e2e/israel1/workload_results/chakra_replay_2024-11-06_17-54-27/Tests.1/0
stdout.txt
```
--------------------------------------------------
+ 1 all_gather
--------------------------------------------------
Size of Input tensors (bytes)
Total (MB)            Max.       Min.       Average           p50           p95
976.56   1024000000.00 1024000000.00   1024000000.00   1024000000.00   1024000000.00
Size of Output tensors (bytes)
Total (MB)            Max.       Min.       Average           p50           p95
7812.50   8192000000.00 8192000000.00   8192000000.00   8192000000.00   8192000000.00 …
```
> Use the latest Chakra replay

- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Bug fix for https://redmine.mellanox.com/issues/4170613
1. CI passes
```
$ python cloudaix.py --log-level DEBUG --log-file run_nemo_gpt3_40b.log run --system-config conf/common/system/israel_1.toml --tests-dir conf/common/test/ --test-scenario conf/devops/verification/test_scenario/nemo_gpt3_40b_nightly.toml
[INFO] Initializing Runner [RUN] mode 
[DEBUG] SlurmRunner initialized
[DEBUG] Executing command for test Tests.1: NCCL_SOCKET_IFNAME=eno8303 NCCL_IB_GID_INDEX=3 NCCL_IB_TC=96 NCCL_IB_HCA=mlx5_0:1,mlx5_3:1,mlx5_4:1,mlx5_5
:1,mlx5_6:1,mlx5_9:1,mlx5_10:1,mlx5_11:1 NCCL_IB_ADAPTIVE_ROUTING=1 NCCL_IB_SPLIT_DATA_ON_QPS=0 NCCL_IBEXT_DISABLE=0 …
```
> Use absolute path for NeMo launcher repository

- src/cloudai/schema/test_template/slurm_container/slurm_command_gen_strategy.py
- tests/ref_data/slurm_container.sbatch
Always mount output path for SlurmContainer. This folder can be used for writing runtime artifacts.
CI, manually
—
> Always mount output path for SlurmContainer

- src/cloudai/report_generator/tool/bokeh_report_tool.py
This PR is the continuation of the PR https://github.com/NVIDIA/cloudai/pull/172.
All the 4 variations of possible generated graphs have been implemented.
1. Single message + Single iteration : We will plot a single point
2. Single message + Multiple iteration : from the PR https://github.com/NVIDIA/cloudai/pull/172
3. Multiple message + Single iteration : existing code
4. Multiple message + Multiple iteration : we will plot the min, max and avg values for the single line graphs (1). For the multi line graphs we will only plot the avgs (2)
(1)
(2)
> Generated graphs

- pyproject.toml
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Fix missing time limit in sbatch script.
1. CI.
2. Local dry-runs and ensure that `--time` is present when `time_limit` is set in scenario.
—
> Fix missing time limit in sbatch script

- src/cloudai/schema/test_template/nemo_run/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
`TestRun.nodes` might contain non-expanded list of nodes like `["nodes1-3"]`, which should be converted to actual list of slurm nodes.
CI.
—
> Fix num_nodes calculation for nemo_run

- src/cloudai/installer/slurm_installer.py
- src/cloudai/systems/slurm/slurm_system.py
- tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
- tests/test_slurm_system.py
The current cloudAI slurm runner fails when many parallel jobs are submitted. The current strategy is to use `squeue` with the job id. However, when many CloudAI jobs are submitted in parallel, some of these jobs might complete at the same time resulting in invalid job id error by the time CloudAI queries this status.
This PR fixes this issue by using an alternative way to determine the job completion status instead of `squeue`. I
CI/CD
Run on real system (Job completion status works and moves on to the next job).
```
(venv) $ python ./clouda
ix.py run --system-config conf/common/system/xxxx--tests-dir conf/common/test --test-scenario conf/nccl_test_nightly.toml 
[INFO] System Name: xxxx
[INFO] Checking if test templates are …
```
> Bug fix for invalid job id for many parallel cloudAI jobs

- src/cloudai/_core/command_gen_strategy.py
- src/cloudai/_core/json_gen_strategy.py
- src/cloudai/_core/test.py
1. Inherit from ABC if there @abstractmethods
2. Do not make gen_srun_success_check() abstruct, simply return an empty string by default. When needed, this method will be overriden.
1. CI.
2. Unfortunately, `ruff` and `pyright` do not catch such issues. Here is pyright's position about it: https://github.com/microsoft/pyright/issues/3952
—
> Fix ABC usage issues

- src/cloudai/_core/base_installer.py
- src/cloudai/installer/slurm_installer.py
- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
Do not check image accessibility from the head node using `enroot`: many systems don't allow such actions. Instead, rely on actual `srun ... enroot import ...` result and report its error to user.
Addresses https://redmine.mellanox.com/issues/4212401.
1. CI
2. Manual on EOS with enabled caching.
For both runs below the failure is expected as test TOML has invalid URL (`docker://DOCKER_IMAGE`).
First run:
```bash
cloudai install --system-config eos.toml --tests-dir conf/common/test/
[INFO] Not all components are ready
[INFO] Going to install 5 item(s)
[INFO] 1/5 Installation of PythonExecutable(git_url=https://github.com/NVIDIA/NeMo-Framework-Launcher.git, commit_hash=599ecfcbbd64fd2de02f2cc093b1610d73854022): OK
[ERROR] 2/5 Installation of …
```
> Do not require enroot on head node

- src/cloudai/test_definitions/nemo_run.py
Fixed typo in NeMoRunTestDefinition. It said it's a test object for NemoLauncher, now it's correctly referring to NeMoRun.
Since I've only edited a comment I haven't tested anything in particular.
> Fixed typo in NeMoRunTestDefinition docstr

- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
This is a PR to mount NCCL_TOPO_FILE to the container when NCCL_TOPO_FILE is set. Previously, a pair of environment variables was used to set NCCL_TOPO_FILE. However, this approach was unnecessary and confusing. With this PR, NCCL_TOPO_FILE is mounted to the container whenever it is available.
Ran it on a server.
> Mount NCCL_TOPO_FILE in NCCL test

- src/cloudai/report_generator/report_generator.py
- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
This is a bug fix for https://redmine.mellanox.com/issues/4248881. @Bohatchuk reported that Chakra replay fails to generate reports when pre-test hooks are enabled. This issue arises from how job completion is checked. Currently, the system checks for specific keywords such as "COMPLETED" in the output of `sacct`. However, when multiple tasks exist within a single job, the output may include a mix of "RUNNING" and "COMPLETED," as shown below:
```
RUNNING
COMPLETED
```
This scenario should be interpreted as the job still running. Otherwise, jobs may be prematurely marked as complete.
1. CI passes
2. Ran on a server (EOS)
```
$ python ./cloudaix.py --log-level DEBUG --log-file run_chakra_replay_3.log run --system-config 
conf/common/system/eos.toml --tests-dir conf/common/test …
```
> Bug fix in job completion checks

- src/cloudai/util/docker_image_cache_manager.py
- tests/test_docker_image_cache_manager.py
Currently the docker image enroot command only contains "account", "partition", "docker image url"
But some clusters may require explicit specify the GPU resource by using `--gpu=N`, like `CW-DFW`
Use Cloudaix to do the testing
- Login into CW-DFW data copy node or login node
- Setup Cloudaix env
- Clone this branch, and install cloudai manually
- Run: `python cloudaix.py install --tests-dir ./conf/staging/dgx_cloud_acceptance_test/test/ --system-config ./conf/common/system/coreweave.toml`
- Confirm if the docker image has been downloaded to ./install successfully
`--gpu=1` will only be added into enroot command when the original command got `Cannot find GPU specification` error
> retry docker image enroot when cluster requires specifying GPU resource

- .github/workflows/ci.yml
- src/cloudai/_core/base_installer.py
- src/cloudai/cli/handlers.py
- src/cloudai/util/__init__.py
- tests/test_base_installer.py
1. If exists and writable, it will be used.
2. If doesn't exist — it will be created.
Extra safety net with permissions check added. Addresses https://redmine.mellanox.com/issues/4259607.
1. CI.
2. Manual dry-run with existing and non-existing output folder.
—
> Unified handling for install and output folders

- src/cloudai/_core/test_scenario_parser.py
- tests/test_test_scenario.py
Bug fix for https://redmine.mellanox.com/issues/4248887. Extend the total time limit to include the time taken by pre/post-test hooks.
1. Added tests.
2. Ran manually
```
$ python ./cloudaix.py dry-run --system-config conf/common/system/israel_1.toml --tests-dir conf/devops/verification/test/ --test-scenario conf/devops/verification/test_scenario/jax_gpt_nightly.toml
```
> Fix time limit calculation to include pre and post test hook durations

- USER_GUIDE.md
- src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/nemo_run/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/slurm_container/slurm_command_gen_strategy.py
- src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- src/cloudai/test_definitions/slurm_container.py
- tests/ref_data/gpt-no-hook.sbatch
- tests/ref_data/gpt-pre-test.sbatch
- tests/ref_data/grok-no-hook.sbatch
- tests/ref_data/grok-pre-test.sbatch
- tests/ref_data/nccl.sbatch
- tests/ref_data/nemo-run-no-hook.sbatch
- tests/ref_data/nemo-run-pre-test.sbatch
- tests/ref_data/slurm_container.sbatch
- tests/ref_data/ucc.sbatch
- tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
1. Always mount current output dir as `/cloudai_run_results`.
2. Introduce `container_mounts(tr)` (final) and `_container_mounts(tr)` (abstract) as part of `SlurmCommandGenStrategy`.
3. Updated tests to match new behavior.
1. CI.
2. For JAX tests current output dir is mounted twice: as `/cloudai_run_results` and as `tdef.cmd_args.setup_flags.docker_workspace_dir`. This is a bit confusing, but works. I ran `srun -n 1 --container-image=nvcr.io/nvidia/pytorch:24.02-py3 --container-mounts=$PWD:/out1,$PWD:/out2 bash` and created files via both mounts, works fine.
3. Run NemoRun and NCCL on IL1.
Nemo Launcher doesn't support new mount as its behavior is significantly different.
> Always mount current output dir as /cloudai_run_results

- conf/common/test/nemo_run_llama3_8b.toml
This is the config tested on docker (nvcr.io/nvidia/nemo:24.12.rc3) thats used by one of the customers. For other customers and other docker url, need to see how to support. 
CI
Tested on real system
```
cloudai run --system-config ../cloudaix/conf/common/system/xxxx --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nemo_run_llama3_8b.toml 
[INFO] System Name: xxxx
[INFO] Test Scenario Name: nemo_run_llama3_8b
[INFO] Test Scenario: nemo_run_llama3_8b
Section Name: nemo_run_llama3_8b_1
Test Name: nemo_run_llama3_8b
Description: dse_nemo_run_llama3_8b …
```
> Base Config for NemoRun LLama3-8b

- src/cloudai/workloads/nccl_test/nccl.py
Allow the `datatype` field to be `uint8` along with `float`
CI
Dry-run
```
(venv) $ cloudai dry-run --system-config ../cloudaix/conf/common/system/xxxx.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nccl_test.toml 
[INFO] System Name: xxxx
[INFO] Test Scenario: nccl-test
Test Name: nccl_test_all_gather
Description: all_gather
[INFO] Initializing Runner [DRY-RUN] mode
[INFO] Submitted slurm job: 0
[INFO] Job completed: Tests.1
[INFO] All test scenario results stored at: …
```
> Allow uint8 in NCCL ALLtoALL

- src/cloudai/workloads/nemo_launcher/report_generation_strategy.py
- tests/report_generation_strategy/test_nemo_launcher_report_generation_strategy.py
Refactor NeMoLauncher report generation to report avg, min, max, and median. NeMoLauncher currently does not generate the same report as NeMoRun ([link](https://github.com/NVIDIA/cloudai/blob/7bdc060dd70ebf7fb7322136c36f7315c09dac48/src/cloudai/workloads/nemo_run/report_generation_strategy.py#L25)). The goal of this PR is to align the report format with NeMoRun by incorporating these statistical measures.
1. CI passes
2. Ran on IL-1
> Refactor NeMoLauncher report generation to report avg, min, max, and median

- src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
- tests/ref_data/nemo-launcher.sbatch
- tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
- tests/test_acceptance.py
When the NeMo Launcher submits multiple jobs, they have the same job name. However, on some Slurm systems, jobs with identical names remain pending even when sufficient nodes are available. To prevent this, I added a timestamp to the job name, allowing multiple jobs to run in parallel.
1. CI passes
2. Ran on IL-1 and EOS
> Ensure unique NeMo Launcher job names using timestamp to avoid conflicts

- src/cloudai/cli/handlers.py
The autoconfigurator feature used in CloudAI so far were simple such as grid search and random walker whose policy was basically stateless and didn't required any policy updates using the feedback. For smarter agents where a policy update is required, it is important to close the loop where the feedback (reward signal) is passed back to the agent. 
This PR is required for smarter agents like BO used in this [PR](https://github.com/Mellanox/cloudaix/pull/175). 
-CI
- Testing on real system (Please look at the test plan for this [PR](https://github.com/Mellanox/cloudaix/pull/175))
> Close the loop on policy update for smarter agents

- src/cloudai/workloads/nccl_test/performance_report_generator.py
- src/cloudai/workloads/nccl_test/prediction_report_generator.py
- tests/report_generation_strategy/test_nccl_prediction_report_generator.py
- tests/report_generation_strategy/test_nccl_report_generation_strategy.py
- Related PR: https://github.com/NVIDIA/cloudai/pull/407
- Related comment: https://github.com/NVIDIA/cloudai/pull/407#discussion_r1995328129
1. CI passes
2. Ran on EOS
```
$ python cloudaix.py run --system-config conf/common/system/eos.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nccl_test.toml
[INFO] Test Scenario: nccl-test
Test Name: nccl_test_all_reduce
[INFO] Submitted slurm job: 2308225
[INFO] Job completed: Tests.1
[INFO] All test …
```
>  Migrate NCCL performance data parsing to performance report generator

- src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
Support 'unknown' cmd args in NCCL cmd generation by getting list of args from actual CmdArgs object.
1. CI
—
> Support 'unknown' cmd args in NCCL cmd generation

- src/cloudai/workloads/nemo_run/nemo_run.py
During real system runs, we encountered a new error/condition that can be incorporated into the constraint checker.
```
Unexpected error: Global batch size must be divisible by the product of micro batch size and data parallel size
Unexpected error: Global batch size must be divisible by the product of micro batch size and data parallel size
```
We already have the `dp`, `gbs` and `mbs` values in the test definition and we should be able to easily check this condition in our constraint checker. This would allow us to catch these run time errors before it gets scheduled from the slurm queue. This PR adds this condition to the constraint checker.
Dry Run with invalid config
odd number of micro_batch_size.
```
[cmd_args.data]
micro_batch_size = [8, 5]
global_batch_size = [64, 128, 256] …
```
> New Constraint Check Nemo2.0

- src/cloudai/_core/reporter.py
- src/cloudai/workloads/nemo_run/report_generation_strategy.py
- tests/report_generation_strategy/test_nemo_run_report_generation_strategy.py
We saw an issue during NemoRun but this could apply to any scenario where the generated stdout has encoded symbols. In Nemo I think this is trigged from the some of the environment variables such as [this](https://github.com/NVIDIA/cloudai/blob/main/conf/common/test/dse_nemo_run_nemotron_15b_fp8.toml#L56) or [this](https://github.com/NVIDIA/cloudai/blob/main/conf/common/test/dse_nemo_run_nemotron_15b_fp8.toml#L65).
The behavior we would like to enforce for these is it should not crash and run to the next test scenario or next step in DSE'ble job.
Example of encoded logs could look like this
```
│[2m                  [0m│     [33mfp8_amax_history_len[0m=[1;36m1024[0m,                            │
│[2m                  [0m│     [33mfp8_amax_compute_algo[0m=[32m'max'[0m, …
```
> Reporting for encoded logs

- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
Fix system serialization. Serialization method should not be a class method: https://docs.pydantic.dev/latest/api/functional_serializers/#pydantic.functional_serializers.field_serializer.
CI.
Thanks @lilyw97 for reporting it.
> Fix system serialization

- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
When 'start_post_init' dependency is used in combination with group-based node list spec, main job might have longer startup time and dependency could allocate all available nodes.
CI.
At this time it is very hard to create a good repro for the issue, we might need some follow up PRs to fix the problem.
—
> Consider only RUNNING state as running job

- src/cloudai/workloads/nemo_run/report_generation_strategy.py
- tests/report_generation_strategy/test_nemo_run_report_generation_strategy.py
Nemo dry-run fails due to a refctor introduced in this PR https://github.com/NVIDIA/cloudai/pull/426
This PR fixes this bug.
CI
Dry-Run
```
cloudai dry-run --system-config ../cloudaix/conf/common/system/xxx.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/dse_nemo_run_llama3_8b.toml 
[INFO] System Name: xxx
[INFO] Test Scenario Name: nemo_run_llama3_8b
[INFO] Test Scenario: nemo_run_llama3_8b
Section Name: dse_nemo_run_llama3_8b_1
Test Name: dse_nemo_run_llama3_8b
Description: dse_nemo_run_llama3_8b
[INFO] Initializing Runner [DRY-RUN] mode
[INFO] Starting test: dse_nemo_run_llama3_8b_1
[INFO] Running test: dse_nemo_run_llama3_8b_1
[INFO] …
```
> Nemo Dry-Run/Run Fix

- src/cloudai/_core/test_scenario_parser.py
- tests/test_test_scenario.py
Make sure error is printed for DSE + unknown metric. Previously it failed silently. Thanks @srivatsankrishnan for finding it.
CI (extended).
—
> Make sure error is printed for DSE + unknown metric

- src/cloudai/_core/test_scenario_parser.py
- tests/test_test_scenario_parser.py
Return None when main test has no time limit in calculate_total_time_limit
Bug fix for https://redmine.mellanox.com/issues/4387329
Test Scenario
```name = "nccl-test"
pre_test = "nccl_test"
[[Tests]]
id = "Tests.1"
test_name = "nccl_test_all_reduce"
num_nodes = "2"
```
Final Sbatch Script
```
#!/bin/bash
#SBATCH --job-name=TestTemplate_20250403_155315
#SBATCH -N 2
#SBATCH --output=results/nccl-test_2025-04-03_15-53-15/Tests.1/0/stdout.txt
#SBATCH --error=results/nccl-test_2025-04-03_15-53-15/Tests.1/0/stderr.txt
#SBATCH --partition=partition_1
#SBATCH --gpus-per-node=8
#SBATCH --gres=gpu:8
#SBATCH --ntasks-per-node=8
#SBATCH --time=00:20:00
export SLURM_JOB_MASTER_NODE=$(scontrol show hostname $SLURM_JOB_NODELIST | head -n 1)
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export …
```
> Return None when main test has no time limit in calculate_total_time_limit

- src/cloudai/cli/handlers.py
Bug fix in src/cloudai/cli/handlers.py
https://github.com/Mellanox/cloudaix/actions/runs/14270984623/job/40003899181?pr=199
```
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
File "/home/runner/work/cloudaix/cloudaix/utils/dgx.py", line 414, in <module>
main()
File "/home/runner/work/cloudaix/cloudaix/utils/dgx.py", line 409, in main
rc = cli.run()
File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/cloudai/cli/cli.py", line 162, in run
return self.handlers[args.mode](args)
File "/home/runner/work/cloudaix/cloudaix/utils/dgx.py", line 353, in handle_dgx_run
handle_dry_run_and_run(args_namespace)
File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/cloudai/cli/handlers.py", …
```
> Bug fix in src/cloudai/cli/handlers.py

- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Support NCCL_TOPO_FILE in all SlurmCommandGenStrategy classes. Currently, NCCL_TOPO_FILE is only supported in NCCL tests. However, this should not be the case, and it should be supported by any Slurm command generation strategy. This PR moves the logic to the parent class, allowing other SlurmCommandGenStrategy implementations to mount NCCL_TOPO_FILE by default. This is one of the LLMB requirements.
CI passes
* Passes `tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py`. It indicates that this change does not break NCCL_TOPO_FILE but only expands its support for general slurm command gen strategy.
> Support NCCL_TOPO_FILE in all SlurmCommandGenStrategy classes

- src/cloudai/systems/slurm/slurm_system.py
Fix: Include CANCELLED+ state in completed job status check
Identified this bug while working on https://github.com/NVIDIA/cloudai/pull/459 on EOS
```
$ sacct -j 2453846 --format=State --noheader
CANCELLED+ 
```
1. CI passes
2. Tested on EOS with https://github.com/NVIDIA/cloudai/pull/459
> Fix: Include CANCELLED+ state in completed job status check

- .github/workflows/ci.yml
- conf/common/test_scenario/sleep.toml
- src/cloudai/_core/base_runner.py
- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
1. Fixed `is_job_running` for slurm system, extended logging to simplify debug for such cases.
2. Removed dry-run test with slurm system from CI, `sacct` is used as a real binary now.
3. Manual runs of sleep scenario, issues were mostly related to `start_post_init` dependency.
—
> Fix is_running for slurm

- src/cloudai/workloads/ucc_test/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
Refactor: Use test definition's cmd_args for UCC command generation
CI passes
> Refactor: Use test definition's cmd_args for UCC command generation

- src/cloudai/systems/slurm/slurm-metadata.sh
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/ref_data/sleep.sbatch
1. Do not filter out Bluefields for NICs' list.
2. Update how CUDA runtime version is fetched.
3. [Fixed](https://redmine.mellanox.com/issues/4402039) path to collection script for bare-metal runs (without container).
1. CI
2. Run `sleep` scenario on EOS, collected metadata looks good.
—
> Updates and fixes for metadata collection

- src/cloudai/workloads/sleep/kubernetes_json_gen_strategy.py
- src/cloudai/workloads/sleep/lsf_command_gen_strategy.py
- src/cloudai/workloads/sleep/standalone_command_gen_strategy.py
Refactor: Use test definition's cmd_args for sleep command generation
CI passes
> Refactor: Use test definition's cmd_args for sleep command generation

- src/cloudai/_core/configurator/base_gym.py
- src/cloudai/_core/configurator/cloudai_gym.py
- src/cloudai/cli/handlers.py
- src/cloudai/workloads/nemo_run/report_generation_strategy.py
- tests/conftest.py
- tests/test_cloudaigym.py
Fix an issue when output_path wasn't updated for test run object. Thanks @srivatsankrishnan for reporting this issue.
2. Manual dry-run, got a failure for `cloudai dry-run --system-config conf/common/system/example_slurm_cluster.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/dse_nemo_run_llama3_8b.toml`, but it is unrelated:
```bash
File "/Users/andreyma/workspace/nvidia/cloudai/src/cloudai/workloads/nemo_run/nemo_run.py", line 143, in constraint_check
constraint3 = gbs % (mbs * dp) == 0
ZeroDivisionError: integer division or modulo by zero
```
3. Run `cloudai run --system-config ../cw.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/dse_nemo_run_llama3_8b.toml` on CW:
```bash
2025-04-11 04:47:52,204 - INFO - Running …
```
> Update output path for DSE runs

- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/systems/slurm/metadata.py
- src/cloudai/systems/slurm/slurm-metadata.sh
- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
1. Collect more information for `SlurmSystemMetadata.slurm`
2. Dump slurm job information once job is completed.
1. CI (expanded)
3. Local dry-run
4. Real run via NCCL perf runner on EOS, `slurm-job.toml` example
```toml
job_id = 2493012
job_name = "coreai_dlalgo_llm-TestTemplate.20250414_024225"
job_state = "COMPLETED"
elapsed_time_sec = 126
srun_cmd = "srun --export=ALL --mpi=pmix --container-image=PATH/_install/nvcr.io_nvidia__pytorch__25.02-py3.sqsh --container-mounts=PATH/cloudaix/results/nccl-perf_2025-04-14_02-42-25/all_reduce/0/1:/cloudai_run_results,PATH/_install:/cloudai_install all_reduce_perf_mpi --nthreads 1 --ngpus 1 --minbytes 8 --maxbytes 16G --stepbytes 1M --op sum --datatype float --root 0 --iters 20 --warmup_iters 5 --agg_iters 1 --average 1 --parallel_init 0 --check 1 …
```
> Collect more metadata for slurm jobs

- src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
Fix typo in src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
CI passes
> Fix typo in src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py

- src/cloudai/workloads/nemo_run/cloudai_nemorun.py
Running Llama3_70b causes an error with `Unexpected error: 'NoneType' object has no attribute 'vocab_size'`
The Vocab_size was set in the [GPT](https://github.com/NVIDIA/NeMo/blob/v2.3.0rc2/nemo/collections/llm/gpt/model/base.py) base model which was setting this value to `None`. Ideally this value should be same as the value in the tokenizer. 
This pR, exposes and sets the value in the `Llama3_70` recipe. 
There was another error related to collectives. This could be a node level issue.  The workaround we have is to set the `check_for_nan_in_grad` to `False`
```
Unexpected error: Rank 40, node cw-dfw-h100-002-295-026, device 0, iteration -1: Unexpected result nan (message='found NaN in local grad norm for bucket #0 in backward pass before data-parallel communication collective') …
```
> Nemo2.0 fixes for Llama70b

- src/cloudai/systems/slurm/metadata.py
- src/cloudai/systems/slurm/slurm-metadata.sh
1. `ompi_version` --> `mpi_version`
2. + `mpi_type`
3. - `nnodes` (duplicated of `num_nodes`).
1. CI
2. Real run on CW, metadata looks valid.
—
> Updates for slurm metadata

- src/cloudai/_core/reporter.py
- tests/test_reporter.py
I realized that CloudAI creates `nemo2.tgz` for `nemo2.0_llama3_70b_fp8_2025-04-16_14-27-45`. This is a bug fix for the bug.
1. CI passes
2. Ran on EOS.
```
$ python cloudaix.py run --system-config conf/staging/llmb/system/eos.toml   --tests-dir conf/staging/llmb/test   --test-scenario conf/staging/llmb/test_scenario/nemo2.0_llama3_70b_fp8.toml 
[INFO] Test Scenario Name: nemo2.0_llama3_70b_fp8
[INFO] Test Scenario: nemo2.0_llama3_70b_fp8
Test Name: nemo2.0_llama3_70b_fp8
Description: nemo2.0_llama3_70b_fp8
[INFO] Submitted slurm …
```
> Fix tarball name to preserve full directory name with dots intact

- src/cloudai/workloads/nemo_run/data_store_report_generation_strategy.py
Prevent NeMoRunDataStoreReportGenerationStrategy from overriding metric logic
- Bug reported by Srivatsan - https://nvidia.slack.com/archives/C088QU7CE3S/p1744919678215499
- Bug introduced by https://github.com/NVIDIA/cloudai/pull/464
**Root Cause**
The `reports` field in `TestRun` is defined as a `set`  
https://github.com/NVIDIA/cloudai/blob/a046d3b0b95191617c1aceaa093333aa2bc00c8d/src/cloudai/_core/test_scenario.py#L70
which means the iteration order is **non-deterministic**.
As a result, when a metric is requested (e.g., `"default"`), the selected report generation strategy may vary between runs.
By default, `NeMoRunDataStoreReportGenerationStrategy` does **not** define its own `metrics` class variable,  
so it inherits `metrics = ["default"]` from the base `ReportGenerationStrategy` …
> Prevent NeMoRunDataStoreReportGenerationStrategy from overriding metric logic

- conf/common/test_scenario/sleep.toml
- src/cloudai/_core/base_runner.py
Because of a bug in the base runner class implementation, even when I set the number of iterations to 3, only the first iteration completes successfully. Although the second iteration is submitted, it is not properly monitored.
```
$ python cloudaix.py run --system-config conf/staging/llmb/system/oci.toml   --tests-dir conf/staging/
llmb/test   --test-scenario conf/staging/llmb/test_scenario/nccl_test.toml 
[INFO] System Name: OCI
[INFO] Test Scenario: nccl-test
Test Name: nccl_test_all_reduce …
```
> Fix premature runner exit by looping until all jobs are complete

- src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
- tests/ref_data/nemo-launcher.sbatch
- tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
- tests/test_acceptance.py
Correctly handle values with spaces for env vars.
1. CI
2. Manually compare a couple of generated commands based on public configs.
—
> Correctly handle values with spaces for env vars

- src/cloudai/cli/cli.py
- tests/test_cli.py
Verify if input path exist on argparse level. It improves the feedback speed and makes error more readable.
Now:
```bash
$ cloudai dry-run --system-config conf/common/system/example_slurm_cluster.tomll --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nemo_launcher.tomll
usage: cloudai dry-run [-h] --system-config SYSTEM_CONFIG --tests-dir TESTS_DIR --test-scenario TEST_SCENARIO [--output-dir OUTPUT_DIR] [--enable-cache-without-check]
cloudai dry-run: error: argument --system-config: Path 'conf/common/system/example_slurm_cluster.tomll' does not exist.
```
Before:
```bash
$ cloudai dry-run --system-config conf/common/system/example_slurm_cluster.tomll --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nemo_launcher.tomll
Traceback (most recent call …
```
> Verify if input path exist on argparse level

- src/cloudai/_core/reporter.py
- src/cloudai/util/base-report.jinja2
- src/cloudai/util/general-report.jinja2
- src/cloudai/util/general-slurm-report.jinja2
Apply style to scenario report. Also extended logging while metadata is collected.
New report looks like this:
1. CI
2. Manual runs of `generate-report`.
—
> Apply style to scenario report

- src/cloudai/workloads/megatron_run/megatron_run.py
- tests/test_test_definitions.py
- tests/test_test_scenario.py
`model_dump()` should include all fields, otherwise construction test with TestScenarion won't be possible.
**NOTE**: this should be a temp solution, going forward we need to find away to remove this limitation.
1. CI
2. Internal slack [channel](https://nvidia.slack.com/archives/C06LC3PRHDZ/p1746910981915689).
—
> Update MegatronRun model dump logic

- src/cloudai/_core/test_scenario_parser.py
- src/cloudai/models/scenario.py
- tests/test_test_scenario.py
Original implementation would fully replace some fields like `cmd_args` with in-scenario value instead of merging values including nested structure. It wasn't visible for Test Definitions when almost all fields have default values.
2. Manually run CloudAIx-based test where this issue was discovered.
—
> Fix how test-in-scenario is merge with test-in-toml

- src/cloudai/installer/slurm_installer.py
- tests/test_slurm_installer.py
This is needed for re-installing. Created folder treated as success indicator for "venv created" event. So if folder exists, but not all requirements are ready, if will fail later and re-running "install" won't help, users have to manually remove folder with venv.
CI (extended)
—
> Remove venv folder if requirements installation failed

- src/cloudai/parser.py
- src/cloudai/systems/slurm/slurm_system.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_slurm_system.py
This PR fixes internal [bug](https://redmine.mellanox.com/issues/4447098). It optimizes how CloudAI communicates with slurm controller and some small improvements:
1. System `update()` should be called before accessing groups, otherwise it leads to error log line like mentioned in the bug. Functionally it was OK though.
2. Introduced `SlurmCommandGenStrategy .get_cached_nodes_spec` to cache node spec details. We need it in different functions and that led to multiple calls to the slurm. It is inefficient and could lead to different node states between runs.
3. Cached system toml loading to avoid re-reading the file.
2. Worked closely with QA to verify the bug and make logging clean and clear.
—
> Optimize slurm updates

- src/cloudai/workloads/slurm_container/slurm_command_gen_strategy.py
- src/cloudai/workloads/slurm_container/slurm_container.py
- tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
- tests/test_test_definitions.py
This PR adds `scripts` and `extra_srun_args` to the `SlurmContainer` test type. 
**Motivation**:  I want to create a test that can download a specified git repo and the scripts needed to build the repo during the installation phase. Additionally, I want this test to run on a single node only, since it's a single-task build job and doesn't need to run on multiple nodes. Therefore, I added these two parameters to support this operation.
CI test
Test Example:
```
name = "build_nccl_test"
description = "build_nccl_test"
test_template_name = "SlurmContainer"
extra_srun_args = ["--ntasks=1", "--ntasks-per-node=1"]
[cmd_args]
docker_image_url = "nvcr.io/nvidia/pytorch:25.02-py3"
cmd = "bash /cloudai_install/build_nccl_test.sh"
[[git_repos]]
url = "https://github.com/NVIDIA/nccl.git"
commit = …
```
> Add extra_srun_args & scripts in SlurmContainerTestDef

- src/cloudai/_core/base_runner.py
- src/cloudai/_core/command_gen_strategy.py
- src/cloudai/_core/reporter.py
- src/cloudai/_core/test_template.py
- src/cloudai/models/scenario.py
- src/cloudai/runner/slurm/slurm_runner.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- tests/test_acceptance.py
- tests/test_reporter.py
Store test details per each case for further reporting. Today it will only be used for single sbatch feature (CloudAIx, separate branch), but we might want to add it into our default reports in future.
2. NCCL run:
```bash
$ cloudai run --system-config ../eos.toml --tests-dir conf/common/test --test-scenario conf/common/test_scenario/nccl_tests_inline.toml 
[INFO] Test Scenario Name: nccl-tests
[INFO] Test Scenario: nccl-tests
Section Name: nccl.all_reduce
Test Name: nccl-all_reduce
Section Name: nccl.all_gather
Test Name: nccl-all_gather
Description: all_gather
[INFO] Creating …
```
> Store test details and best config for DSE

- src/cloudai/installer/slurm_installer.py
- tests/ref_data/nixl_bench.sbatch
- tests/test_slurm_installer.py
1. Use `--copies` when creating a venv to allow mounting it into a container.
2. Fix tests caused by unordered PRs merge.
1. CI
2. Manual runs of installation for venvs.
—
> Use copies for venv creation + fix tests

- src/cloudai/systems/slurm/slurm_system.py
- src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
- src/cloudai/workloads/slurm_container/slurm_command_gen_strategy.py
- tests/ref_data/nixl_bench.sbatch
- tests/ref_data/slurm_container.sbatch
- tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
- tests/test_acceptance.py
Add an option for Slurm system to control if home folder should be mounted (default is yes for slurm). CloudAI's default is `false`, so `--no-container-mount-home` is added by default.
_Note_: I've set `slurm_system.container_mount_home = True` for acceptance tests to avoid multiple changes in ref files. A unit test for this behavior was added.
1. CI (extended).
—
> Control if home folder should be mounted into container for slurm

- src/cloudai/workloads/nemo_run/nemo_run.py
This ensures compatibility with Pytorch lightning and fixes #543. 
CI
—
> Allow val_check_interval to be int, float, or list of both

- src/cloudai/_core/base_installer.py
- src/cloudai/installer/slurm_installer.py
- tests/test_base_installer.py
- tests/test_slurm_installer.py
When system's `.cache_docker_images_locally` is not set to `true`, `_install_path` shouldn't be set and URL should be used instead.
CI (extended)
—
> Make sure mark_as_installed respects system config

- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
Refactor supports_gpu_directives to focus on GresTypes
1. Related Chat: https://nvidia.slack.com/archives/C06LC3PRHDZ/p1749064907087079
2. Related PR: https://github.com/NVIDIA/cloudai/pull/541
1. CI passes
2. Ran on servers
EOS
```
python cloudaix.py run --system-config conf//common/system/eos.toml --tests-dir conf/devops/verification/test/ --test-scenario conf/devops/verification/test_scenario/nemo_run_pretrain_fp8_nightly.toml
```
CW
```
python cloudaix.py run --system-config conf//common/system/cw.toml --tests-dir conf/devops/verification/test/ --test-scenario conf/devops/verification/test_scenario/nemo_run_pretrain_fp8_nightly.toml
```
IL-1
```
python cloudaix.py run --system-config conf//common/system/israel_1.toml --tests-dir conf/devops/verification/test/ --test-scenario …
```
> Refactor supports_gpu_directives to focus on GresTypes

- USER_GUIDE.md
- src/cloudai/_core/test_scenario_parser.py
- src/cloudai/cli/cli.py
- src/cloudai/cli/handlers.py
- src/cloudai/runner/slurm/single_sbatch_runner.py
- src/cloudai/util/__init__.py
- src/cloudai/util/utils.py
- tests/test_acceptance.py
- tests/test_cli.py
- tests/test_registry.py
- tests/test_single_sbatch_runner.py
Add single sbatch runner for slurm systems: all cases are put into a single sbatch file instead of per-case sbatch files. Some notes:
1. Max number of nodes is chosen automatically based on cases description.
2. DSE cases are unrolled using grid search strategy, agent spec is ignored.
3. Dependency specifications are ignored, cases run one by one.
4. Each case results are still placed into own folder, `test-run.toml` is created per case.
5. `slurm-job.toml` is created per whole job and doesn't contain real command lines.
6. All reports work the same way.
7. New CLI option `--single-sbatch` enables it on Slurm systems, raises an error on others.
—
> Add single sbatch runner for slurm systems

- src/cloudai/cli/handlers.py
Reports are currently not generated for DSE jobs. This PR addresses the issue. We will revisit the gym design and architecture at a later time. This is intended as a temporary fix.
1. CI passes
2. Ran on CW
```
$ python cloudaix.py --log-level DEBUG run --system-config conf//common/system/cw.toml --tests-dir conf/./devops/verification/test/ --test-scenario ./conf/./devops/verification/test_scenario/dse_nccl_test.toml
```
```
$ ls
cloudai_nccl_test_bokeh_report.html  cloudai_sbatch_script.sh  mapping-stderr.txt  metadata    stdout.txt
cloudai_nccl_test_csv_report.csv     env_vars.sh               mapping-stdout.txt  stderr.txt  test-run.toml
```
> Generate reports for DSE jobs

- src/cloudai/systems/slurm/slurm_installer.py
- tests/test_slurm_installer.py
In some environments using `--copies` leads to the error. It can happen for `uv`-created venvs. Fixes [internal bug](https://redmine.mellanox.com/issues/4474900).
1. CI
2. Manual runs of installation.
—
> Do not use --copies for venv creation

- src/cloudai/systems/slurm/slurm_metadata.py
- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_system.py
Fix parsing `sacct` information when `srun` has a multiline command.
Fixes [internal bug](https://redmine.mellanox.com/issues/4501538).
1. CI (extended).
—
> Fix for handling srun with multiline commands

- src/cloudai/workloads/bash_cmd/__init__.py
- src/cloudai/workloads/bash_cmd/bash_cmd.py
- tests/slurm_command_gen_strategy/test_bash_cmd_slurm_command_gen_strategy.py
Add `BashCmd` workload. It is a simple bash command without `srun` prefixes.
1. CI
2. Manually tested as part of https://github.com/Mellanox/cloudaix/pull/192.
—
> Add BashCmd workload

- src/cloudai/models/scenario.py
- tests/test_reporter.py
- tests/test_test_definitions.py
Correctly load and save test definition objects as part of `TestRunDetails`.
1. CI (extended).
—
> Correctly load and save tdef as part of TestRunDetails

- src/cloudai/systems/slurm/slurm_node.py
- src/cloudai/systems/slurm/slurm_system.py
- tests/test_slurm_allocation.py
- tests/test_slurm_system.py
Re-worked slurm node status update to prepare for [internal bug](https://redmine.mellanox.com/issues/4471870) fix:
1. Take into account both `sinfo` and `squeue` results for nodes' info.
2. Incapsulate cli tool calls with relevant parsing into a single function.
3. Added tests including one that reproduces the issue, to be fixed in the following PR (or PRs).
1. CI
—
> Re-work slurm node status update

- src/cloudai/systems/kubernetes/kubernetes_runner.py
Align method with BaseRunner by renaming to on_job_completion and removing async
- Bug introduced by https://github.com/NVIDIA/cloudai/pull/567
- Prerequisite for #579
CI passes
> Align method with BaseRunner by renaming to on_job_completion and removing async

- src/cloudai/systems/kubernetes/kubernetes_installer.py
Add DockerImage support to Kubernetes installer methods
Currently, caching docker images in K8s servers is not supported. Consider that all pass successfully.
Prerequisite for #579
1. CI passes
2. Ran on a K8s server by rebasing https://github.com/NVIDIA/cloudai/pull/579 to this one.
https://drive.google.com/drive/folders/1NIjhcGsdIek9O5LIDyd8gcKiiyyUYDNc?usp=drive_link
> Add DockerImage support to Kubernetes installer methods

- src/cloudai/_core/test_template.py
Match json_gen_strategy implementation to command_gen_strategy
Spin-off this PR to focus on missing store_test_run in json_gen_strategy in https://github.com/NVIDIA/cloudai/pull/584
CI passes
> Match json_gen_strategy implementation to command_gen_strategy

- src/cloudai/workloads/nixl_bench/nixl_summary_report.py
Silently skip NIXL summary generation if no NIXL tests.
1. CI.
2. Manual runs of `run` and `generate-report`.
—
> Silently skip NIXL summary generation if no NIXL tests

- src/cloudai/workloads/nemo_run/cloudai_nemorun.py
- src/cloudai/workloads/nemo_run/nemo_run.py
- src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
The request is to enable Llama3 405b on B200/GB200. The FSDP is now supported in Nemo2.0 however, it doesn't currently work with TP [[1](https://github.com/NVIDIA/NeMo/blob/main/scripts/performance/utils.py#L349)] and certain comm overlap [[2](https://github.com/NVIDIA/NeMo/blob/main/scripts/performance/utils.py#L349)] parameters.
This PR adds new feature sets for Nemo2.0 for Llama3 405b (target):
[Update]: FSDP support
- There is a bug that prevents FSDP to be functional: https://gitlab-master.nvidia.com/dl/JoC/nemo-ci/-/issues/2422
- The fix for the above issue will be available in Nemo container 25.07.rc3 (not available yet). 
Layer Recomputation (Potential to save memory)
Offload specific activation layer to CPU
References:
[1] [TP disabled with …
> Llama31_405b 

- src/cloudai/systems/slurm/slurm_command_gen_strategy.py
Fix confusing folder structure with `.../post_test/pre_test/...`.
Fixes [internal bug](https://redmine.mellanox.com/issues/4496929).
1. CI.
—
> Avoid confusing post_test/pre_test folder structure

- src/cloudai/_core/test_template_strategy.py
- src/cloudai/systems/lsf/lsf_command_gen_strategy.py
- src/cloudai/systems/slurm/slurm_command_gen_strategy.py
- src/cloudai/test_parser.py
- src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
- src/cloudai/workloads/nccl_test/kubernetes_json_gen_strategy.py
- src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
- src/cloudai/workloads/nixl_bench/slurm_command_gen_strategy.py
- src/cloudai/workloads/triton_inference/slurm_command_gen_strategy.py
- tests/json_gen_strategy/test_nccl_runai_json_gen_strategy.py
- tests/slurm_command_gen_strategy/test_bash_cmd_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nixl_bench_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_sleep_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_triton_inference_slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
- tests/test_acceptance.py
- tests/test_get_job_id.py
- tests/test_single_sbatch_runner.py
- tests/test_slurm_system.py
1. It wasn't used for long time, same args come via TestRun object.
2. Constructor simplified to accept only system, args are not needed.
3. Additionally, removed _override_cmd_args as it was used in combination with default_cmd_args only.
1. CI.
—
> Remove default_cmd_args field from TestTemplateStrategy

- conf/common/test/dse_nemo_run_llama3_8b_bf16.toml
- src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Handles comma in env vars values for NemoLauncher. Fixes issue #557.
1. CI
—
> Handles comma in env vars values for NemoLauncher

- src/cloudai/_core/installables.py
- src/cloudai/systems/slurm/docker_image_cache_manager.py
- tests/test_base_installer.py
- tests/test_docker_image_cache_manager.py
There are two changes here: 
- using --ntasks=1 when downloading docker images to ensure there are no parallel downloads
- replacing `#` in docker image url with `_` to avoid shell issues.
Added UT and verified manually.
> Docker cache fix

- src/cloudai/workloads/nixl_perftest/__init__.py
- src/cloudai/workloads/nixl_perftest/nixl_perftest.py
- src/cloudai/workloads/nixl_perftest/slurm_command_gen_strategy.py
- tests/slurm_command_gen_strategy/test_nixl_perftest_slurm_command_gen_strategy.py
Introduce custom matgen script args support. Along with any option, set correct `ppn` value.
Fixes [internal bug](https://redmine.mellanox.com/issues/4548555).
2. Manual dry-run:
```bash
$ uv run cloudai dry-run --system-config ../cloudaix/conf/devops/verification/system/pre-tyche.toml --test-scenario ../cloudaix/conf/devops/verification/test_scenario/kvbench_ctperf.toml
$ cat results/KVBenchCTPerf_2025-07-29_15-34-18/KVBenchCTPerf.1/0/cloudai_sbatch_script.sh| grep matgen | grep ppn | wc -l
1
```
—
> Support custom matgen args and set valid ppn

- conf/common/test/dse_nccl_all_gather.toml
- conf/common/test/nccl_test.toml
- conf/common/test/nccl_test_all_gather.toml
- conf/common/test/ucc_test.toml
- conf/common/test_scenario/nccl_test.toml
- conf/hook/test/nccl_test_all_gather.toml
- conf/release/nemo_acceptance/test/nccl_test_all_reduce_loopback.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_gather.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_gather_worst.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_reduce.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_reduce_worst.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall_worst.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall_worst_failover.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_bisection.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_broadcast.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_gather.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_hypercube.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce_scatter.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce_scatter_worst.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_scatter.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_sendrecv.toml
- conf/release/spcx/l40s/test/l40s-bc-nccl_test_sendrecv_worst.toml
Replace PyTorch image tag from 24.02-py3 to 25.06-py3 in all conf TOML files
[RM4548252](https://redmine.mellanox.com/issues/4548252)
Performed
```
$ find conf -type f -name "*.toml" -exec sed -i '' 's|nvcr.io/nvidia/pytorch:24.02-py3|nvcr.io#nvidia/pytorch:25.06-py3|g' {} +
$ find conf -type f -name "*.toml" -exec sed -i '' 's|nvcr.io/nvidia/pytorch:25.02-py3|nvcr.io#nvidia/pytorch:25.06-py3|g' {} +
```
Related PR: https://github.com/Mellanox/cloudaix/pull/322
1. CI passes
2. Run on CW
```
$ cloudai install --system-config ../cloudaix/conf/common/system/cw.toml --tests-dir conf/common/test
[INFO] System Name: Coreweave
[INFO] Not all components are ready
[INFO] Going to install 5 item(s)
[INFO] 1/6 Installation of …
```
> Replace PyTorch image tag from 24.02-py3 to 25.06-py3 in all conf TOML files

- src/cloudai/util/__init__.py
- tests/test_base_installer.py
Improve prepare_output_dir error handling for permissions and read-only fs
[RM4540741](https://redmine.mellanox.com/issues/4540741)
1. CI passes
2. Run on laptop
```
$ ueue --states=running,pending --noheader -o '%P|%T|%N|%u'': /bin/bash: squeue: command not found
[INFO] System Name: example-cluster
[ERROR] Output path '/install_dir' is not writable.
[INFO] Test Scenario: nccl-test
Section Name: Tests.all_reduce
Test Name: nccl_base_test
Description: NCCL base test configuration
Section Name: Tests.all_gather
Test Name: nccl_test_all_gather
Description: all_gather
Start Post Comp: Tests.all_reduce
Section Name: Tests.reduce_scatter
Test Name: nccl_base_test …
```
> Improve prepare_output_dir error handling for permissions and read-only fs

- tests/test_base_installer.py
Improve prepare_output_dir error handling for permissions and read-only fs (continued)
https://github.com/NVIDIA/cloudai/pull/629
https://github.com/NVIDIA/cloudai/pull/629#discussion_r2262500135
CI passes
> Improve prepare_output_dir error handling for permissions and read-only fs (continued)

- src/cloudai/workloads/ai_dynamo/report_generation_strategy.py
- tests/report_generation_strategy/test_ai_dynamo_report_generation_strategy.py
Report generation was working fine for the last release ([v1.3.0](https://github.com/NVIDIA/cloudai/releases/tag/v1.3.0)), but it started failing after https://github.com/NVIDIA/cloudai/pull/615. This is due to multiple sections being printed in the genai-perf results.
**[RM4554591](https://redmine.mellanox.com/issues/4554591): AI Dynamo reporter needs to handle extra lines in genai-perf profile.csv**
**Isssue 1: AI Dynamo runs successfully, but the report generation stage fails (`[WARNING] Error generating report...`)**
```
$ python cloudaix.py run --system-config conf/common/system/cw.toml --tests-dir conf/staging/ai_dynamo/test --test-scenario conf/staging/ai_dynamo/test_scenario/deepseek_r1_distill_llama_8b.toml   
...
[WARNING] Error generating report for …
```
> Handle multi-section CSV format in AI Dynamo report generation

- src/cloudai/_core/test_scenario.py
- tests/test_cloudaigym.py
Preserve installables' state during `apply_params_set()`.
Fixes [internal bug](https://redmine.mellanox.com/issues/4554582).
2. Run on EOS, make sure cached path is used for etcd docker image.
—
> Preserve installables' state during apply_params_set()

- src/cloudai/workloads/nixl_bench/slurm_command_gen_strategy.py
Control which env vars dumped for per-rand evaluation for NIXL bench to avoid confusing warnings.
Fixes [internal bug](https://redmine.mellanox.com/issues/4554504).
1. CI
2. Runs on EOS, check that `env_vars.sh: line 1: scontrol: command not found` message is gone.
—
> Control which env vars dumped for per-rand evaluation

- src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
Follow up for [PR641](https://github.com/NVIDIA/cloudai/pull/641) (Support for DeepSeekR1 model with SGLang / AI Dynamo)
**Resolved by this PR**
1. Use _gpus_per_node ([link](https://github.com/NVIDIA/cloudai/pull/641#discussion_r2278015139))
2. prefill-initialized-regex from TOML ([link1](https://github.com/NVIDIA/cloudai/pull/641#discussion_r2278015867), [link2](https://github.com/NVIDIA/cloudai/pull/641#discussion_r2278016229))
3. Partially resolved - Initializing prefill-cmd ([link](https://github.com/NVIDIA/cloudai/pull/641#discussion_r2277998091))
* My response
* It is okay to have an initial value. This does not prevent users from specifying prefill-cmd.
* Updated the sglang.toml file to set prefill-cmd as we did for vllm.toml (https://github.com/Mellanox/cloudaix/pull/332). …
> Follow-up for PR641 (Support for DeepSeekR1 model with SGLang / AI Dynamo)

- src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
Refactor GPU count to use _gpus_per_node in vllm and env validation
Follow-up PR for https://github.com/NVIDIA/cloudai/pull/653
Comment https://github.com/NVIDIA/cloudai/pull/653#discussion_r2279537492
1. CI passes
2. Run on EOS
**VLLM**
```
$ python cloudaix.py run --system-config conf/common/system/eos.toml --tests-dir conf/staging/ai_dynamo/test --test-scenario conf/staging/ai_dynamo/test_scenario/deepseek_r1_distill_llama_8b.toml 
[INFO] Test Scenario Name: deepseek_r1_distill_llama_8b
[INFO] Test Scenario: deepseek_r1_distill_llama_8b
Test Name: vllm
Description: vllm
[INFO] Starting …
```
> Refactor GPU count to use _gpus_per_node in vllm and env validation

- src/cloudai/workloads/ai_dynamo/ai_dynamo.py
- src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
- src/cloudai/workloads/ai_dynamo/slurm_command_gen_strategy.py
Refactor nodelist validation to check DYNAMO_NODELIST only if both args empty
Follow up for [PR641](https://github.com/NVIDIA/cloudai/pull/641) (Support for DeepSeekR1 model with SGLang / AI Dynamo)
**@karya0's comments resolved by this PR**
1. https://github.com/NVIDIA/cloudai/pull/641#discussion_r2278002812
2. https://github.com/NVIDIA/cloudai/pull/641#discussion_r2278004082
Relies on https://github.com/NVIDIA/cloudai/pull/655
1. CI passes
2. Run on EOS
**VLLM LLAMA8b works**
```
$ python cloudaix.py run --system-config conf/common/system/eos.toml --tests-dir conf/staging/ai_dynamo/test --test-scenario conf/staging/ai_dynamo/test_scenario/deepseek_r1_distill_llama_8b.toml 
[INFO] Test Scenario Name: deepseek_r1_distill_llama_8b
[INFO] …
```
> Refactor nodelist validation to check DYNAMO_NODELIST only if both args empty

- src/cloudai/reporter.py
- tests/test_reporter.py
Handle single-sbatch metadata layout in report.
Fixes [internal bug](https://redmine.mellanox.com/issues/4582416).
2. Manual run and check result html.
—
> Handle single-sbatch metadata layout in report

- src/cloudai/workloads/nixl_bench/report_generation_strategy.py
- tests/report_generation_strategy/test_nixl_bench_report.py
Recently NIXL bench introduced new output format that we need to support. Keep old format supported as well for transition period.
2. Manual runs with old and new containers, checked output and reporting.
—
> Support two NIXL bench output formats

- src/cloudai/models/scenario.py
Make agent_reward_function configurable
Taken from https://github.com/karya0/cloudai/commits/aug25/ (https://github.com/karya0/cloudai/commit/e830aa14b7b2bf0a28218756ee9bc547fbb531e3#diff-dfa9eccbd1a274f636a1278a9691b69d9273b2a6b5a956a11febe23aa791e268)
[RM4604577](https://redmine.mellanox.com/issues/4604577)
1. CI passes
2. Verified by @karya0. This commit is added at Kapil's request.
> Make agent_reward_function configurable

- src/cloudai/_core/base_installer.py
- src/cloudai/cli/handlers.py
Automatically install missing components for workloads in run mode, so users can just `run` instead of seeing annoying message that `install` should be executed first.
1. CI
2. Manual runs with some components missing.
—
> Auto install missing components for workloads in run mode

- .github/workflows/ci.yml
- src/cloudai/cli/cli.py
- src/cloudai/cli/handlers.py
- src/cloudai/parser.py
- src/cloudai/test_parser.py
- src/cloudai/test_scenario_parser.py
- tests/test_cli.py
- tests/test_test_definitions.py
Get rid of strict validation for configs as it is not used and only confuses users.
Fixes [internal bug](https://redmine.mellanox.com/issues/4540313).
1. CI (updated)
—
> Get rid of strict validation for configs

- conf/common/test/dse_nemo_run_llama3_8b_bf16.toml
- conf/common/test/dse_nemo_run_llama3_8b_fp8.toml
- conf/common/test/nemo_run_llama3_8b.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_bf16_128_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_bf16_256_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_bf16_2_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_128_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_16_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_256_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_2_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_32_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_4_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_64_node.toml
- conf/experimental/test/nemo_launcher_nemotron_15b_fp8_8_node.toml
- conf/release/nemo_acceptance/test/nemo_run_llama3_8b.toml
Update Nemo image reference to nvcr.io#nvidia/nemo:25.07 in all toml files
1. CI passes
2. Ran on CW. Please see https://github.com/Mellanox/cloudaix/pull/352
> Update Nemo image reference to nvcr.io#nvidia/nemo:25.07 in all toml files

- src/cloudai/cli/handlers.py
- tests/test_handlers.py
Provide a concise summary of the changes introduced by this pull request. Detail the purpose and scope of the changes, referencing any relevant issues or discussions. Explain how these changes address the problem or improve the project.
Fixes [internal bug](https://redmine.mellanox.com/issues/4539540).
1. CI (extended).
2. Run `dry-run` using configs from the bug:
```bash
...
[INFO] System Name: example-cluster
[INFO] Test Scenario Name: ncclint-test
[INFO] Checking if workloads components are installed.
[INFO] Test Scenario: ncclint-test
Section Name: Tests.all_reduce
Test Name: ncclint_base_test
Description: NCCL internal plugin base test configuration
Section Name: Tests.reduce_scatter
Test Name: ncclint_base_test
Description: NCCL internal …
```
> Explicitly forbid dependencies for scenarios with DSE jobs

- conf/common/test/dse_nemo_run_llama3_8b_fp8.toml
Vboost as a feature requires sudo access to the nodes. The public facing configuration cannot make this assumption regarding sudo access and hence needs to be removed.
-CI/CD
- Real system
> Removing VBOOST 

- uv.lock
Add `uv.lock` for persistent env. This will also improve security checks of our dependencies.
1. CI
2. Manual sync + use this branch in CloudAIx.
—
> Add uv.lock for persistent env

- src/cloudai/cli/cli.py
- src/cloudai/cli/handlers.py
- src/cloudai/registration.py
- tests/test_registry.py
Allow agents to be registered via [entry points](https://packaging.python.org/en/latest/specifications/entry-points/). This will allow easier agents distribution and usage: private agents can be installed into CloudAI env.
Additionally, extended `cloudai list` command to accept `agents` argument.
2. Real run with private agent via [CloudAIx](https://github.com/Mellanox/cloudaix/pull/368).
—
> Allow agents to be registered via entry points

- src/cloudai/workloads/nemo_run/cloudai_nemorun.py
- src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
We deprecated Llama3_8b for Gb200 systems VER testing. As a replacement, we add Qwen3_30b model for GB200. This PR adds support for Qwen3_30b model using existing Nemo-Run mechanisms.
-CI/CD
- Real Gb200 internal cluster. Logs here.
> Add Qwen Recipe (VER)
